### ISSUE TITLE
Recategorize some items from Pets.json

### ISSUE THREAD

**Issue by Xzandro** [WFCD/warframe-items#101]
So in the past few weeks I was pretty involved in the data this repo produces (great work btw.) and I think there are some inconsistencies in the Pets.json.
I expected only Pets itself from this file, but there are also a bit more unrelated items in there. I created an exclusion list for my project and maybe it makes sense to apply these here also.

`['KubrowPetFood', 'BlankTraitPrint', 'EggHatcher', 'CatbrowGeneticSignature', 'KubrowEgg', 'KubrowPetCollarItem']`
All of these items from the Pets.json are probably better mapped to Misc imo.

Also

- Add Moa's to the file `misc.filter(m => m.uniqueKey.includes('MoaPetHead'))`
- Maybe add Venari too

**Comment by TobiTenno** [comment]
for those, we'll need to check their unique ids and see what's common in them, and ascribe them a specific type
