### ISSUE TITLE
Sort by name or Drop Chance? (or both?)

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#105]
The data seems to thrash a good bit because of the sorting we do on drop chances.

Right now it looks like we're sorting by drop chance, but i'm questioning if we should sort by chance or by something more static like the location so that the order in the array doesn't change so much and the user can sort as needed, but with less changes on our data for otherwise unneeded reasons (specifically when they're received in a different order, but the same drop chance, causing changes to data ordering without any actual data changes)

Alternatively, drop rate, then sub-sort by location? this would provide the value that's present now, but without the thrashing we're getting with lexicographically randomly reordering

**Comment by esunder** [comment]
@TobiTenno the sorting looks like it’s by name/unique name, no?
https://github.com/WFCD/warframe-items/blob/development/build/build.js#L69

**Comment by TobiTenno** [comment]
not for the drops for each item

**Comment by esunder** [comment]
ah, i see. thanks for the link

**Comment by TobiTenno** [comment]
np, sorry i didn't add it before 😞
