### ISSUE TITLE
Warframe Augment Mods listed as non tradable

### ISSUE THREAD

**Issue by Nakroma** [WFCD/warframe-items#107]
A lot of the warframe augment mods (https://warframe.fandom.com/wiki/Warframe_Augment_Mods), if not all (I didn't test everything), are listed as `tradable: false` even though they are tradable.

Examples:

- Guided Effigy
- Mesa's Waltz
- Seeking Shuriken
- Fracturing Crush
- Vampire Leech

**Comment by TobiTenno** [comment]
Any pattern in the unique IDs for exilus mods? It's come up a few times but we've not found any adequate identifier to separate and distinguish them.

**Comment by Nakroma** [comment]
I'm not sure that this correlates with Exilus Mods, for example Gale Kick and Aviator are correctly marked as tradeable, and except Mesa's Waltz none of the examples above is an exilus mod

**Comment by TobiTenno** [comment]
Sorry, I meant augments

**Comment by Nakroma** [comment]
The `uniqueName` String seems to end with "AugmentCard", have you already checked that?

**Comment by TobiTenno** [comment]
nope. i must've really been crossing my wires when i responded originally. I'll take a look when I can.

Self notes:
- Add type for `Augment` with id `AugmentCard`
- Add `Augment` type to tradeable types
