### ISSUE TITLE
Tekko Prime is not flagged as a fist weapon

### ISSUE THREAD

**Issue by codemastermick** [WFCD/warframe-items#109]
Tekko Prime's type listing shows as melee but should probably be under the Fist type

**Comment by codemastermick** [comment]
I can open a PR with the corrected data for Tekko Prime if you guys like, just let me know

**Comment by codemastermick** [comment]
fixed by 84b30c3788e46b15e4cc95c97b89d2003657fa68

**Comment by TobiTenno** [comment]
ty for the offer, many of these get fixed by DE fixing their data upstream, thankfully.

**Comment by codemastermick** [comment]
Due to the nature of the app that I am working on, I see a lot of these problems crop up pretty quickly. I maintain a number of switch statements in my code that handles some of these edge cases. Would these be helpful to provide to you guys when they come up, or should I let things alone unless they are at least X months old and probably not going to get fixed by DE?

Sent from Mail for Windows 10

**Comment by TobiTenno** [comment]
it'd be best if you put them all in an issue of their own, after checking through the old issues and seeing if it's been discussed before or not resolved for other reasons. that makes them the easiest to review and make decisions on.
