### ISSUE TITLE
Overrides dont work

### ISSUE THREAD

**Issue by esunder** [WFCD/warframe-items#113]
JavaScript utilizes pass-by-sharing for objects, not pass-by-reference:
https://stackoverflow.com/a/38533677

This function does not modify the object that is passed into it 
https://github.com/WFCD/warframe-items/blob/development/build/parser.js#L727

An example of this is ExcaliburPrime is overridden to be tradeable: false in overrides.json, but it is still set to true in the Warframes.json
https://github.com/WFCD/warframe-items/blob/development/data/json/Warframes.json#L9862

**Comment by esunder** [comment]
I found this while working on the Kubrow Collar. I can include a fix in that PR if wanted.

**Comment by TobiTenno** [comment]
i mean it works for everything else, lol

**Comment by TobiTenno** [comment]
otherwise none of the other functions would work either
