### ISSUE TITLE
Prime Vault items are considered as "vaulted"

### ISSUE THREAD

**Issue by Zayceur** [WFCD/warframe-items#118]
Today two warframes (Valkyr & Saryn Prime) are part of the Prime Vault but the API returned them as "vaulted". What does actually mean the "vaulted" variable ?

For me the "vaulted" variable means the relics looting the items aren't lootable anymore.

Could someone please clarify this situation ?

Thanks,

Zayceur

**Comment by TobiTenno** [comment]
mmm, it technically means their primary relics were moved to the vault. when a "prime vault" is out, there are separate relics. if i remember right, the vaulted logic is basically just "is it currently after the `vaultDate` value?" true means vaulted, false means not

**Comment by Zayceur** [comment]
Wouldn't it be better to define "vaulted" like this pseudo-code :

```
fun isVaulted(item) {
    if item has components {
        if each component isn't vaulted {
           return false
        } else {
            return true
        } 
    }

    if item can loot from relics {
        if one of the relic isn't vaulted {
            return false
        } else {
            return true
        }   
    } 

    // if none of the precedent conditions apply
    return currentDate >= vaultDate
}
```

**Comment by TobiTenno** [comment]
not really, cause that'd involve searching all of its relics, which would also involve finding all of it's component, and we're trying to make the build faster, not slower.... technically even "opening the prime vault" items are still vaulted, they're just out of it for a short bit.... it's honestly a logical mess, cause nothing stays vaulted forever.
