### ISSUE TITLE
Forma drops missing from main Forma entry

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#120]
**Describe the bug**
The main entry for Forma (`"/Lotus/Types/Items/MiscItems/Forma"`) does not list any drops for the main item or its Blueprint. Forma Blueprint's drops are available in a wide variety of other places where it is used in a recipe, but not here.

**Expected behavior**
Forma item entry should include drops.

Forma BP drops appear to have been removed in 3e889f9e86d1036c8263f4637d942e44ce7616d7.

**Comment by TobiTenno** [comment]
Hey @AlyoshaVasilieva, I'm definitely seeing it on at least 1.697.0, could you verify if [this runkit works for you](https://runkit.com/embed/q9jvl4s88lir), both in runkit and if your run locally?

**Comment by TobiTenno** [comment]
Probably related to the now-closed #121

**Comment by AlyoshaVasilieva** [comment]
Drops reappeared in 1fbbf94f, so it appears fixed.
