### ISSUE TITLE
Kuva Ayanga classified as a primary weapon, should be arch-gun

### ISSUE THREAD

**Issue by IanBullard** [WFCD/warframe-items#122]
**Describe the bug**
The Kuva Ayanga Archgun is listed in the Primary.json instead of Archwing.json.

**To Reproduce**
1. Go to data/json/Primary.json
2. Search for "Kuva Ayanga"
3. See arch-gun listed in primary weapon data

**Expected behavior**
I'd expect the Kuva Ayanga to be listed in the Archwing.json data file.

**Additional context**
See https://warframe.fandom.com/wiki/Kuva_Ayanga.  The unique name is /Lotus/Weapons/Grineer/HeavyWeapons/GrnHeavyGrenadeLauncher

**Comment by TobiTenno** [comment]
Could you follow the whole template? It helps us diagnose and fix things faster. Specifically, I need to find the unique I'd of the ayanga cause I'm guessing it needs a separate filtering for it's type.

**Comment by TobiTenno** [comment]
also, i think the main problem is it's not being marked as archwing, because all other arch-guns are marked simply archwing, not something specific to heavy weapon

**Comment by IanBullard** [comment]
Sorry, first bug report I've ever made in Github.

**Comment by TobiTenno** [comment]
oh, all good, just discussing it. i've not seen it not render the :bug: actually, that's too bad.

anyway, i'm working on branching out the archguns
