### ISSUE TITLE
List Sentinel Weapons separately from secondary weapons.

### ISSUE THREAD

**Issue by IanBullard** [WFCD/warframe-items#123]
**Is your enhancement request related to a problem? Please describe.**
While not difficult to filter, I think it's misleading to list sentinel weapons in Secondary.json

**Describe the upgrade you'd like**
List sentinel weapons in Sentinels.json or SentinelWeapons.json instead.

**Describe alternatives you've considered**
I'm currently filtering if unique name contains "SentinelWeapons" and I'm more than willing to continue to do so.

**Comment by TobiTenno** [comment]
I'd be happy to add a sub-type, but technically they still fit in their existing categories

**Comment by TobiTenno** [comment]
My meaning is that "primaries", "secondaries", and "melee" aren't specifically only to the co-op/conclave loadout. it's shard with sentinel & archwing types. i'm considering doing the same for archwing, but i'm gonna have to get @Kaptard or some others to weigh in, cause that's a pretty hefty (usability) change

**Comment by IanBullard** [comment]
Understood, it's just a thought on my end and I'm happy to defer to those more knowledgable.

**Comment by TobiTenno** [comment]
I don't think it's a bad thought, I just worry it'd be a big breaking change.

**Comment by TobiTenno** [comment]
I'm going to be adding a distinct 'type' so they at least have a difference.

**Comment by TobiTenno** [comment]
@IanBullard i've found that they have a distinct 'productCategory', i'll add this as a standalone category for these

**Comment by IanBullard** [comment]
Cool, thank you!

**Comment by TobiTenno** [comment]
question, are you trying to use this through `All.json`, or the specific category?

problem will be that there'll be a new category file that i'm making, but the category on the object won't change, so if you're doing a filter on the json based on the category field, this won't help you.

**Comment by IanBullard** [comment]
I'm using the specific category, so that works for me.

**Comment by TobiTenno** [comment]
cool!
