### ISSUE TITLE
Some items have `primeSellingPrice` but not `ducats`

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#124]
**Describe the bug**
The relevant components for Ivara Prime, Aksomati Prime, and Baza Prime are missing `ducats` (edit: fixed in 5b04891e5c067cae86f38cb4301a38ed6ee7f8ca). However, all but the Blueprint *do* have `primeSellingPrice`, which appears to be ducats. `primeSellingPrice` appears to be present and a duplicate of `ducats` in a wide variety of items (311 items have `primeSellingPrice`, 378 have `ducats`).

**Expected behavior**
All items with ducat value have ducats listed in exactly one field.

**Versions:**
 - Version: 1.729.0
- Access Method: GitHub

**Comment by AlyoshaVasilieva** [comment]
Additionally: The `ducats` field is correct (100) for Valkyr Prime Systems, but `primeSellingPrice` is incorrect (45).

**Comment by TobiTenno** [comment]
Prime selling price is handed off from DE. We don't control accuracy of fields except where it's something we programmatically determine.

**Comment by TobiTenno** [comment]
I've updated this to rely on ducats, so ducats _should_ always get set, and primeSellingPrice will remain, but could be removed at some point.
