### ISSUE TITLE
JSON not being updated

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#134]
The data in /data/json hasn't been updated since Feb 29, but new items have been added to the game.

https://github.com/WFCD/warframe-items/tree/development/data/json

**Comment by TobiTenno** [comment]
we're takin a look. they're definitely updating on the released npm artifacts, but just not in the repository itself

**Comment by Richasy** [comment]
Hi @TobiTenno , I tried the npm package, but it is clear that the new weapons and Warframe (such as Titania Prime) have not been updated. Looking at the recent update records, it seems that repository is only updating `package.json`, and there are no actual entries added.

**Comment by TobiTenno** [comment]
Yeah, I was definitely wrong, I was looking for older items, not the newest ones. We're looking into it.

**Comment by Kaptard** [comment]
Sorry that this took so long to figure out. The proxy we're using refused to connect without throwing errors. I'll push a commit to remove the proxy entirely as manual builds on the VPS seem to work now, whereas before they were blocked by DE's reverse proxy.

**Comment by TobiTenno** [comment]
ty so much, kilian!
