### ISSUE TITLE
Weapons reclassified as Misc type

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#137]
**Describe the bug**
bdf92dbbce753077329c8fedfeac4277251412ee reclassified many items as Misc, even when it seems not to make sense. Browsing through the changes to Primary.json show almost every primary weapon being changed to `Misc` type. This seems like a bug or at least very strange.

**Comment by TobiTenno** [comment]
hmmm, that doesn't seem right. It's likely the change I made to the wiki data overwriting existing good data. I'll change how tha that works.

to specify, it reclassified the `type`, not `Category`.

**Comment by TobiTenno** [comment]
fix and rebuild is out. lemme know if that fixes what you're experiencing, @AlyoshaVasilieva

**Comment by AlyoshaVasilieva** [comment]
Seems to have fixed it, thanks!
