### ISSUE TITLE
:rocket: Endo Tables for mods

### ISSUE THREAD

**Issue by tomas1207** [WFCD/warframe-items#142]
**Is your enhancement request related to a problem? Please describe.**
If you can add endo table for mods to make a bluiders app possible

**Comment by TobiTenno** [comment]
All of our data is either generated or overrides afterwards, it'd be rather cum ersome to manually keep a table of Endo values up to date.

**Comment by TobiTenno** [comment]
If you have a method of calculating the Endo value based on rarity/rank, then that would be most welcome.

**Comment by tomas1207** [comment]
you can scrap from wiki?

**Comment by tomas1207** [comment]
I did a small script in pyhton before start use yours lib and i get the endo tables from the wiki https://github.com/tomas1207/ModEndo
