### ISSUE TITLE
Moa & K-drives in respective categories

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#143]
**Is your enhancement request related to a problem? Please describe.**
Modular Moa & K-drives recently became secondaries in the data

**Describe the upgrade you'd like**
Modular Moa should probably get "forcibly" categorized as Pets
K-drives may need some sort of "vehicles" category

**Describe alternatives you've considered**
- leaving them as secondaries: doesn't really make sense, since they're not

**Additional context**
N/A

**Comment by Xzandro** [comment]
Imo  we could do it like this:

- K-Drives: misc
- MOA: companions
- Zaws: melee
