### ISSUE TITLE
Drops missing for new relics

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#145]
New relics (27.5.6 unvaulting): Axi S7, Neo N12, Meso D5, Lith K4

These relics all exist as items in `All.json` but no item lists them as a location for drops.

All of these relics appear in the official drop tables with their items and they are also present on the wikia.

**Comment by dimon222** [comment]
CI broke seems. The scraper itself is working.

**Comment by TobiTenno** [comment]
I'm running a manual build and i'll get it pushed out to development in a few hours.

**Comment by TobiTenno** [comment]
I guess minutes instead of hours. They're now in the development branch.
