### ISSUE TITLE
Sentinel weapon in primary weapon data

### ISSUE THREAD

**Issue by turulix** [WFCD/warframe-items#147]
Hey

Im not sure if this is how its supposed to be but the sentinel weapons (Artax, etc...) are inside the primary.json. I don't think they are supposed to be in there because there is a separate file for those.

**Comment by TobiTenno** [comment]
they are supposed to be in there as they're sentinel primaries. not all of them are, like i believe the deconstructor is under melee? it's based on what mods they accept (or it should be based on that)
