### ISSUE TITLE
:bug: Various Mods Missing

### ISSUE THREAD

**Issue by JonathanSourdough** [WFCD/warframe-items#148]
**Describe the bug**
Multiple mods are missing from mods.json:

Primed Smite Corrupted
Swift Deth
Helminth Ferocity
Scan Lifeforms
Warrior
Enguard
Striker
Retarget

**Versions:**
 - Version v1.944.0
- Access Method: github download

**Comment by JonathanSourdough** [comment]
Also missing Expel Corpus.

**Comment by TobiTenno** [comment]
We don't generate the list of them, so if they're missing from the list, we don't really have a way of pulling them in unless we're filtering them out...

**Comment by JonathanSourdough** [comment]
Oh, I see. Something particularly interesting, last week when I downloaded the mods.json, it did include the "Expel Corpus" mod, but now it does not. Sadly I overwrote the file so I cant present it. But I imagine its in the commit history somewhere a week ago, if anyone cares to take a look at that.

**Comment by TobiTenno** [comment]
Yeah, I don't doubt you, the problem is we don't store history in the builds... I am, however, seeing the mod in the copy we serve from our api [here](https://api.warframestat.us/items/search/expel%20corpus)
