### ISSUE TITLE
:bug: Valkyr Prime Systems BP has wrong ducat value

### ISSUE THREAD

**Issue by dimon222** [WFCD/warframe-items#149]
**Describe the bug**
This is what `All.json` shows:
![image](https://user-images.githubusercontent.com/2671025/87226531-5b0cd380-c362-11ea-9821-4c2fb29f919c.png)

This is what official api has:
![image](https://user-images.githubusercontent.com/2671025/87226537-652ed200-c362-11ea-93eb-aeb391691e78.png)

This is what wiki has:
![image](https://user-images.githubusercontent.com/2671025/87226546-6e1fa380-c362-11ea-871c-64ba07fb842d.png)

Somehow we still end up with 45, how happen?

**Comment by tezf** [comment]
This is interesting. By DE's conventions, Valk's systems should have had it's ducat value decreased from 100 to 65 when it was released as an uncommon drop in Axi V9. But the wiki and in game both shows 100 ducat. Might be an oversight from DE's perspective, but no insight into how this becomes 45 instead.

**Comment by TobiTenno** [comment]
sorry it's been a bit, doing some testing on it right now to see where the value is precisely coming from. what's likely happening is.... 

```
addDucats (item, ducats) {
    if (!item.name.includes('Prime') || !item.components) return
    for (const component of item.components) {
      if (component.primeSellingPrice) component.ducats = component.primeSellingPrice

      if (!component.tradable || component.ducats) continue
      const composite = `${item.name} ${component.name}`;
      const wikiaItem = ducats.find(d => d.name.includes(`${item.name} ${component.name}`))
      if (wikiaItem) {
        component.ducats = wikiaItem.ducats
      } else {
        warnings.missingDucats.push(`${item.name} ${component.name}`)
      }
      if (composite === 'Valkyr Prime Systems') {
        console.log(`is VPS wiki item? ${wikiaItem}`)
        console.log(`wiki ducks: ${wikiaItem.ducats}`)
        console.log(`other ducks: ${component.primeSellingPrice}`)
      }
    }
  }
```

up on the `continue` line, it's likely getting a bad value from DE's data

**Comment by F3l1XQu1ll** [comment]
Can you tell me the link to DEs raw data? I remember some kind of mirror side for it.

**Comment by dapal-003** [comment]
The android manifests indicate that it should be 100 ducats

**Comment by TobiTenno** [comment]
i can point you to how we grab it, but it's a multi-step process.

Grab this url: `http://content.warframe.com/PublicExport/index_en.txt.lzma`

Then unzip it, open up the file and download the applicable file from this format: `http://content.warframe.com/PublicExport/Manifest/${endpoint}`

**Comment by TobiTenno** [comment]
Yeah, I'm gonna let it just always fall into the wikiItem.ducats instead of only falling back if there's no value, just getting those changes in and tested

**Comment by TobiTenno** [comment]
looking correct on the repo now, i'll go ahead and close this
