### ISSUE TITLE
:bug: wisp components incomplete drop location data

### ISSUE THREAD

**Issue by WarNote** [WFCD/warframe-items#150]
**Describe the bug**
The data that it should output in a component of the wisp would be "Jupiter - The Ropalolyst" instead we get "Jupiter - The".

**To Reproduce**
1. Go to 'https://api.warframestat.us/items/search/wisp'
2. Scroll down to '"name": "wisp"'
3. See the components location data

**Comment by TobiTenno** [comment]
Fixed, the name shows correctly on the components as of #156
