### ISSUE TITLE
:bug: Pangolin Prime vaulting data incorrect

### ISSUE THREAD

**Issue by R-Jimenez** [WFCD/warframe-items#151]
**Describe the bug**
Pangolin Prime (`/Lotus/Weapons/Tenno/Melee/Swords/PrimePangolinSword/PrimePangolinSword`) has incorrect vault metadata:
```
"vaultDate": "2020 05 30",
"estimatedVaultDate": "2020 05 30",
"vaulted": true
```
The sibling items (Titania Prime and Corinth Prime) are correct.

**To Reproduce**
Go to https://api.warframestat.us/items/search/pangolin%20prime and view the response.

**Expected behavior**
Show same vault information as sibling items:
```
    "vaultDate": "n/a",
    "estimatedVaultDate": "2021 07 04"
```

**Comment by R-Jimenez** [comment]
Mesa Prime's set also has her and the sibling items listed as vaulted in July, whereas it seems to other sources she'll be around till potentially October.

**Comment by TobiTenno** [comment]
we don't maintain that data, it's pulled in from elsewhere, so that's not something we can correct manually or force new values into
