### ISSUE TITLE
:bug: Missing wikiaThumbnail attribute for Equinox and Equinox Prime Warframe

### ISSUE THREAD

**Issue by F3l1XQu1ll** [WFCD/warframe-items#152]
**Describe the bug**
The wikiaThumbnail attribute for the Equinox and Equinox Prime Warframe is missing.

**To Reproduce**
1. Query https://api.warframestat.us/warframes/search/equinox
2. Search for the wikiaThumbnail attribute - is missing for both entries
3. I can confirm that this is not an API issue since the data is also missing in the raw file 

**Expected behavior**
The response should contain this attribute as it does for every? other item.

- Access Method: [github download, warframestatus api]

**Additional context**
Not a big deal since all images are also separated accessible, but it should match with the other entries.

**Comment by TobiTenno** [comment]
Those are entirely dependent on the url populating from the wiki data, can't do anything if it's not in their data

**Comment by F3l1XQu1ll** [comment]
Closing then, thank you for the info.
