### ISSUE TITLE
:bug: Incorrect image for Fass Residue

### ISSUE THREAD

**Issue by faibz** [WFCD/warframe-items#153]
**Describe the bug**
The image for Fass Residue is incorrect.

**To Reproduce**
1. Go to 'warframe-items/data/img/'
2. Open 'fass-residue.png'
3. See error (is a picture of Otak Token).

**Expected behavior**
Should show a picture of Fass Residue. but currently shows a picture of an Otak Token.

**Screenshots**
![image](https://user-images.githubusercontent.com/24656251/91745044-47d3f280-ebb2-11ea-8d77-bc7ff32539e3.png)

**Comment by TobiTenno** [comment]
we don't determine the images. we consume what is provided from DE's image manifests. if you can find where that is incorrectly being used, let us know.

**Comment by faibz** [comment]
![image](https://user-images.githubusercontent.com/24656251/92180521-29365b80-ee3f-11ea-85d0-953a89f415c0.png)
https://nexushub.co/warframe/items/fass-residue

Does this count?

**Comment by TobiTenno** [comment]
no, like where in our code it's being set wrong.

"used wrong" as in used wrong from their data.

nexushub consumes warframe-items
