### ISSUE TITLE
Can you split All.json?

### ISSUE THREAD

**Issue by Cyl18** [WFCD/warframe-items#159]
**Is your enhancement request related to a problem? Please describe.**
yes, I'm using jsdelivr, and it shows that it exceeds the max file size of 20 MB
![image](https://user-images.githubusercontent.com/14993992/97099446-1e23dd00-16c4-11eb-9e27-717ef1b0f984.png)

**Describe the upgrade you'd like**
Split the json file data/json/All.json into some small files

**Describe alternatives you've considered**
use 7z or, idk, if you don't agree with that, I'll find another way😊

**Additional context**
I'm currently working on a chatbot that needs the All.json data(keep updated), but in my region, GitHub raw is too slow(20kb/s), or even can't be accessed, so we use CDN to download files.

thanks.

**Comment by SlayerOrnstein** [comment]
Technically All.json is already split into smaller files, all the jsons in data/json are just added into it. So you could probably just iterate and download each one then use that data to make you're own json file in you cdn.

**Comment by TheRealKamisama** [comment]
> 
> 
> Technically All.json is already split into smaller files, all the jsons in data/json are used to create it. So you could probably just iterate and download each one then use that data to make you're own all.json file in your cdn.

I got the rewards in each relic from content.warframe.com in the form of uniquename, I need to translate it into human-readable names.
But the problem is I can't know what type the rewards are, Melee or Primary parts, Warframe or Archwing parts.
I could go through all the possible jsons, but if something changes in the future, I need to add possible jsons to my code.
Well, now I'm using cloudflare to download the raw resources from github, you can consider to 7zip it in the future.

**Comment by SlayerOrnstein** [comment]
I'm just saying as a temporary solution you could gather the json under data to create your own all.json because that's we create it. We take all the json and put it under one file. And you would only have to get them once every week/month.

**Comment by Cyl18** [comment]
> I'm just saying as a temporary solution you could gather the json under data to create your own all.json because that's we create it. We take all the json and put it under one file. And you would only have to get them once every week/month.

thanks😁

**Comment by TobiTenno** [comment]
you can also just use our api (https://api.warframestat.us/items) that feeds the whole json when you want it, and then cache it
