### ISSUE TITLE
Drop sources for Hikou under Panthera ingredients show Hikou Prime relics

### ISSUE THREAD

**Issue by semlar** [WFCD/warframe-items#161]
In [/warframe-items/blob/development/data/json/Primary.json](https://github.com/WFCD/warframe-items/blob/development/data/json/Primary.json), the ingredient list for Panthera shows "Hikou", but lists relic drop locations for "Hikou Prime"

![hikou](https://user-images.githubusercontent.com/365191/99178125-2200b900-26de-11eb-89cf-17e81bd725b0.png)

**Comment by TobiTenno** [comment]
yeah, this was a known risk when we changed the drop matching to build faster... if you have any suggestions, feel free to suggest a different string matching for [here](https://github.com/WFCD/warframe-items/blob/development/build/parser.js#L571)

**Comment by semlar** [comment]
What is the purpose of checking `drop.item.startsWith(item)` in the filter, can you give some examples of items that is intended to match?

**Comment by TobiTenno** [comment]
i'd think we'd need to do the same for all of the similar modifiers (wraith, vandal, etc.) so switching to a regex would be the ideal.

the intention is to catch things like forma, where we may not have a component for their blueprint separately, necessarily, or in case such items arise in the future.

**Comment by TobiTenno** [comment]
I've got a test written up for hikou, but i'm going to work on a couple others to make sure i'm asserting them consistently
