### ISSUE TITLE
All.json is empty

### ISSUE THREAD

**Issue by ausanc** [WFCD/warframe-items#166]
The [All.json file](https://github.com/WFCD/warframe-items/blob/development/data/json/All.json) is empty as of commit https://github.com/WFCD/warframe-items/commit/2cd5a4649e02f67f10354fe44f552d054bdc26f9.

**Comment by TobiTenno** [comment]
sadly I can't do much about this as it generates fine locally and appears to be a bug with the bot's release process, which I can't affect.

**Comment by TobiTenno** [comment]
should be resolved thanks to #170 and subsequent changes
