### ISSUE TITLE
Component lists for components of Warframes are missing

### ISSUE THREAD

**Issue by ausanc** [WFCD/warframe-items#167]
**Describe the bug**
The chassis, systems, and neuroptics of non-prime warframes should have a list of components, but these are missing.
For example, the Ash listing in Warframes.json lists the chassis component like so:
```
{
  "uniqueName": "/Lotus/Types/Recipes/WarframeRecipes/AshChassisComponent",
  "name": "Chassis",
  "description": "Chassis component of the Ash Warframe.",
  "itemCount": 1,
  "imageName": "chassis.png",
  "tradable": false,
  "drops": [
    {
      "location": "Grineer Manic",
      "type": "Ash Chassis Blueprint",
      "chance": 0.1278,
      "rarity": "Common"
    }
  ]
},
```
Which is missing a components list of Morphics, Ferrite, and Rubedo.

https://github.com/WFCD/warframe-items/issues/59 suggests this data should be in Misc.json, but it appears to be missing from there too, with no search results for the Ash chassis uniqueName `/Lotus/Types/Recipes/WarframeRecipes/AshChassisComponent`, while it is present in [the Misc.json file a year ago](https://raw.githubusercontent.com/WFCD/warframe-items/4780a5d99cc916ebd8bb52ede5868942544b5c12/data/json/Misc.json)

**Comment by TobiTenno** [comment]
sorry i'd not responded at all... best I can tell it's something where the warframe components got gone from the data, but I'm still looking into it, since that's probably not the case

**Comment by TobiTenno** [comment]
yeah, they gutted it, sorry.
