### ISSUE TITLE
No falloff typings for typescript

### ISSUE THREAD

**Issue by Tc-001** [WFCD/warframe-items#171]
**Describe the bug**
There are no typescript typings for Item.AreaAttack.falloff

**To Reproduce**
1. Open visual studio code
2. Create a index.ts file
3. paste in the following:
```ts
import Items from 'warframe-items'
const items = new Items({ category: ['Primary'] })

let this_line_will_error = items[0].areaAttack.falloff
```
**Expected behavior**
There is no typescript error, as falloff is a possible attribute

**Screenshots**
![image](https://user-images.githubusercontent.com/55956895/106498116-99690c00-64c7-11eb-8117-938128fc9cf3.png)
![image](https://user-images.githubusercontent.com/55956895/106499068-c8cc4880-64c8-11eb-93a4-12040d15ea4a.png)

**Versions:**
 - Node.js version: v14.15.4
 - npm version: 6.14.10
 - Version 1.1245.0
- Access Method: npm package

**Additional context**
This should be a simple fix of adding the necessary typings to the index.d.ts file
If needed, I can attempt to fix it and send in a pull request.

**Comment by TobiTenno** [comment]
feel free to submit a PR. I don't run anything ts with this right now, so i have no good way of adding tests for typings. if you know of a good typings test action/framework, i'd be happy to try it.

**Comment by Tc-001** [comment]
Sure, turns out that is is much easier than I thought to make it.

I do not have experience with testing typescript, so I don't know how much I can help.
But one thing that I can think of is to run the raw json file through something similar to http://json2ts.com/ or https://www.npmjs.com/package/json-schema-to-typescript and that can be used to check, or maybe build the .d.ts file depending how smart the package is. (if that is something that you wish to do)

**Comment by TobiTenno** [comment]
the problem is that, due to the data mirroring what DE provides, new fields will always have to be manually added, as i understand typescript and DE's non-passive changes.
