### ISSUE TITLE
[Discussion] Scoping package to allow new releases

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#174]
**Is your feature request related to a problem? Please describe.**
At present, we're unable to release new versions due to @Kaptard being the only contributor besides @nexus-ci, which does not function at present.

**Describe the solution you'd like**
I'd like to propose scoping warframe-items to `@wfcd/warframe-items` on npm so that we can release new versions. If he ever returns or we have a way to publish to main warframe-items again, we can start releasing there. At present, I can't even push a fix to force drone to not break things and just do releases.

**Describe alternatives you've considered**
- [x] contacting @Kaptard (hasn't responded)
- [x] adding myself as a contributor in the package.json (doesn't actually give me publish access)

**Additional context**
We aren't really sure what's up with @Kaptard, so we need a workable go-forward plan.

**Comment by SlayerOrnstein** [comment]
I think forking, even if temporary would be the only way to get a release if they're MIA.

**Comment by TobiTenno** [comment]
this is essentially forking via npm, we'd just change the package title in the package.json and i'd go release it.

the advantage is that this would preserve tags and make it an easy switch back

**Comment by TobiTenno** [comment]
I'm gonna wait to see how the output of #170 goes, here's hoping it'll get drone running properly?

**Comment by TobiTenno** [comment]
well, the merge from #170 worked, so i guess i may just need to have an automator like what @Xzandro did, just only on master instead of dev... or push it them merge development into master so it keeps the current process?

**Comment by Xzandro** [comment]
Both ways should work. There are [actions](https://github.com/marketplace/actions/merge-branch) where you can merge automatically from one branch to another.

**Comment by TobiTenno** [comment]
got it working just building on master, so we'll probably destroy dev soon, since it's not needed. Thanks for the help, y'all!

**Comment by TobiTenno** [comment]
Guess it's time to reopen this, as the bot is not longer releasing

**Comment by TobiTenno** [comment]
got the bot to release the right one again, closing again, re-pinning,
