### ISSUE TITLE
Master Build failing due to lua parsing errors

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#179]
**Describe the bug**
Lua parsing errors seem to be caused in a change in data format from the lua assets we try to pull from for adding in wiki data.

**To Reproduce**
1. Run build
2. Build errors parsing lua data

**Expected behavior**
Build does not error parsing lua data

**Screenshots**

**Versions:**
 - Node.js version: [e.g. v8.16.0] v14.14.0
 - npm version: [e.g. v6.11.0] v7.6.3
 - Version [e.g. v1.576.0] v1.1246.37
- Access Method: [e.g. npm package, github download, warframestatus api] github

**Additional context**

**Comment by JLP0578** [comment]
Hello,
I have the same error when I build the project with npm.
The incriminated file is **"./tmp/dataraw.lua"**
I put you attached a screenshot of my terminal with the error

![terminal_lua_bug_warframe-items](https://user-images.githubusercontent.com/54902345/114200130-2f506580-9955-11eb-81f8-a42599bf76ac.PNG)

Thank you in advance

**Versions:**
Node.js version: v12.19.0
npm version: v6.14.8
lua version: 5.1.5
Version v1.1246.38

**Comment by TobiTenno** [comment]
yup, we definitely knew about it with that error. thanks!

**Comment by TobiTenno** [comment]
Looks like the wiki changed their lua structure away from what the script that modified the lua data was expecting. i've got a fix prepped to do a bit more intelligent removal, but i'm seeing some errors fetching images as well that i'll probably need to fix before pushing this one out

**Comment by TobiTenno** [comment]
fixed with 3e6fa91dea89172ddc064ef1f390c81cf0b6232c
