### ISSUE TITLE
:bug: Mausolon are listed 3 times in Primary.json

### ISSUE THREAD

**Issue by andersbrandt** [WFCD/warframe-items#180]
**Describe the bug**
Mausolon are listed 3 times in https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Primary.json

**Expected behavior**
Mausolon are listed 1 time

**Comment by TobiTenno** [comment]
_insert recurring "please don't use raw github, use [the API](https://api.warframestat.us/items) or [the module](https://npmjs.com/package/warframe-items)" here_

I'm hoping that my changes on f0b36be8d2a2caa17a1be38c9853e26f1cb234e3 fix the duplication. They did locally, but I like letting the bot builds do the work of getting json generated

**Comment by TobiTenno** [comment]
closed with https://github.com/WFCD/warframe-items/commit/f0b36be8d2a2caa17a1be38c9853e26f1cb234e3
