### ISSUE TITLE
Missing 'releaseDate' properties

### ISSUE THREAD

**Issue by NathanEyre** [WFCD/warframe-items#184]
It would be nice to be able to pull the release date right from the Warframe object.

If a property called 'releaseDate' could be added onto the Warframe items that stores a release date in a YYYY-MM-DD format such as '2021-03-17'.

I do see that there is an 'introduced' property that notes what patch its from (E.g. 'Vanilla') but there are no details to cross reference the dat the items was actually released.

**Comment by NathanEyre** [comment]
Sorry, I now see that that exact 'releaseDate' field is in the data for non vanilla objects. Closing this out.

**Comment by NathanEyre** [comment]
After investigating there are a lot of Warframes missing this data. There must be values being missed by the parser. 

I don't know enough about the source data or the scraping/parsing routines to diagnose the issue. 

My findings are below and the first thing to notice is that almost all the Prime Warframes with the exception of Excalibur Prime have a release date on the object whereas Warframes that are not Prime do not.

### Has Release Dates
Ash Prime, Atlas Prime, Banshee Prime, Chroma Prime, Ember Prime, Equinox Prime, Frost Prime, Gara Prime, Hydroid Prime, Inaros Prime, Ivara Prime, Limbo Prime, Loki Prime, Mag Prime, Mesa Prime, Mirage Prime, Nekros Prime, Nezha Prime, Nova Prime, Nyx Prime, Oberon Prime, Octavia Prime, Rhino Prime, Saryn Prime, Titania Prime, Trinity Prime, Valkyr Prime, Vauban Prime, Volt Prime, Wukong Prime, Zephyr Prime

### Missing Release Dates
Ash, Atlas, Banshee, Baruuk, Bonewidow, Chroma, Ember, Equinox, Excalibur, Excalibur Prime, Excalibur Umbra, Frost, Gara, Garuda, Gauss, Grendel, Harrow, Hildryn, Hydroid, Inaros, Ivara, Khora, Lavos, Limbo, Loki, Mag, Mesa, Mirage, Nekros, Nezha, Nidus, Nova, Nyx, Oberon, Octavia, Protea, Revenant, Rhino, Saryn, Sevagoth, Titania, Trinity, Valkyr, Vauban, Volt, Wisp, Wukong, Xaku, Zephyr

**Comment by TobiTenno** [comment]
something you might've noticed is that the ones with release dates are prime, the others are not
that would lead me to believe these come from our ogg data (which we don't maintain), so this isn't something we can repopulate

**Comment by NathanEyre** [comment]
I did noticed that. That's a bummer, thanks for giving us a heads up. I'll try to find another way to get that data and close this issue.

**Comment by TobiTenno** [comment]
if you find another way, i'd be happy to integrate it into the build so it's useful for everyone

**Comment by NathanEyre** [comment]
I did find another way. 

I'm not sure if the same data resides in your source but the wiki has a json file containing all the version data:
https://warframe.fandom.com/api.php?action=query&titles=Module:Version/data&prop=revisions&rvprop=content&format=json

After the its just a matter of cross referencing your warframe item's 'introduced' property to the Wikis version item's 'Name'  or 'Aliases' property.

**Comment by TobiTenno** [comment]
that doesn't look parseable at all... we'd probalby need to parse that through our lua bits

**Comment by TobiTenno** [comment]
We'll wanna look at adding this: https://warframe.fandom.com/wiki/Module:Version/data?action=edit
