### ISSUE TITLE
:bug: Data inconsistency for weapons with relics only available from Baro

### ISSUE THREAD

**Issue by FarBeyondDriven** [WFCD/warframe-items#185]
**Describe the bug**
Data inconsistency for weapons with relics only available from Baro:

Aklex Prime: "tags" : ["Prime","Baro"]
Akvasto Prime: "tags" : ["Prime","Vaulted"]

**To Reproduce**
Fetching json data for secondary weapons and/or all weapon data

**Expected behavior**
Both weapons should have the same tag array, and both should have the "Baro" tag, so it should be either:

Aklex Prime: "tags" : ["Prime","Baro"]
Akvasto Prime: "tags" : ["Prime","Baro"]

or 

Aklex Prime: "tags" : ["Prime","Vaulted","Baro"]
Akvasto Prime: "tags" : ["Prime","Vaulted","Baro"]

**Additional context**
I don't really mind which option to go with, but it should be consistent for both Baro weapons, and at least they should both indicate that they are available from Baro, ie getting the "Baro" tag.

**Comment by TobiTenno** [comment]
your best bet is modifying.... https://warframe.fandom.com/wiki/Module:Weapons/data?action=edit to add the tags you're thinking of
