### ISSUE TITLE
:bug: Primary Weapon Kuva Bamma missing wikia thumbnail field

### ISSUE THREAD

**Issue by FarBeyondDriven** [WFCD/warframe-items#186]
**Describe the bug**
The Primary Weapon **Kuva Bamma** is missing the wikia thumbnail field "_wikiaThumbnail_"

**To Reproduce**
Fetching jsondata for primary weapons or all weapon data

**Expected behavior**
wikiaThumbnail should be set to "https://static.wikia.nocookie.net/warframe/images/a/a7/Kuva_Bramma.png/revision/latest?cb=20210609234150"

**Additional context**
That should be the proper url, but any url with the right image will do of course.

**Comment by TobiTenno** [comment]
Still not quite sure on this one

**Comment by TobiTenno** [comment]
eyyyy, found it. the imageUrls map that we're using for getting images from wikia (it's a map from them) mapped the image title for it as `Kuva Bramma.png`, whereas the image name in the weapons lua is `Kuva_Bramma.png`... gg wikia :D
