### ISSUE TITLE
[Bug] stancePolartiy property missing on melee weapons

### ISSUE THREAD

**Issue by Melfyce** [WFCD/warframe-items#213]
### Describe the bug

Melee weapons are missing their stance polarities

### NodeJS Version

14.17.1

### npm Version

7.20.0

### warframe-items Version

v1.1248.5

### Access Method

warframestat.us API

### What happened?

Hello :-)
This is the first time I do this so please bear with me.
I have noticed that every melee weapon is missing its stancePolartiy property. (I have noticed this for the first time about 2 weeks ago)
Is this intended or a bug? I also have an older version of warframe-items and compared some melee weapons with the ones from the latest warframe-items version to be sure it's not just one or two weapons where this problem occurs.

**Comment by TobiTenno** [comment]
i'll do a local build and see if they just dropped off, but my guess is DE dropped the data or it's gone from wherever we were pulling it from

**Comment by TobiTenno** [comment]
looks like they mapped them to the standard values instead of the weird ones on the wikia, and we hadn't adjusted for that

**Comment by Melfyce** [comment]
> looks like they mapped them to the standard values instead of the weird ones on the wikia, and we hadn't adjusted for that

thank you, now it is working perfectly!
