### ISSUE TITLE
[Bug] Missing damage types of weapons

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/warframe-items#214]
### Describe the bug

All weapons are missing their relative damage types

### NodeJS Version

14.17.0

### npm Version

6.14.13

### warframe-items Version

1.1248.9

### Access Method

github download

### What happened?

All of the weapons for some reason doesn't have damage types anymore. I have no ideia in which version this did occur, but both api and repository are missing it.

**Comment by TobiTenno** [comment]
sure, i'll take a look
