### ISSUE TITLE
[Bug] Adaptation tradable set to false

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/warframe-items#215]
### Describe the bug

The adaptation mod tradable key is set to false as it's value

### NodeJS Version

14.17.0

### npm Version

6.14.13

### warframe-items Version

1.1248.9

### Access Method

npm Package (Default)

### What happened?

As you can see in the image it's supposed to be tradable, so it's value should be true.
![Adaptation_trading](https://user-images.githubusercontent.com/42449362/126363445-85934edf-8f47-49dc-9fcd-27ea00058648.png)

**Comment by AyAyEm** [comment]
It seems that adaptation has duplicated unique name entries, one of which tradable is se to false.
The unique names are:
- "/Lotus/Upgrades/Mods/Nemesis/AvatarSentientArmourMod" (tradable: false)
- "/Lotus/Upgrades/Mods/Warframe/AvatarResistanceOnDamageMod" (tradable: true)

**Comment by TobiTenno** [comment]
fixed with bb64aaa0b1cdfa38401241457d6871f86710e4b2
