### ISSUE TITLE
Arcanes aren't tracked

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#22]
It seems all arcanes except the new ones (including arcane helmets) are missing from Arcanes.json. Not sure which exports file they're in either. This shouldn't be hard to implement - Just find the export URL and add the required condition to the export type in `scraper.addCategory`.

**Comment by TobiTenno** [comment]
By virtue of how they're made, I don't think arcanes will show up as an export, because they don't show anywhere in the mobile app and would, theoretically, otherwise show up in the aranes and relics manifest

**Comment by TobiTenno** [comment]
I think i've got it sorted now for all those i could find in our data... I'll keep looking to see if i can find the helmets

**Comment by TobiTenno** [comment]
Looks like we definitely have Arcane helmets in our skins data, so i think that's sufficient
