### ISSUE TITLE
[Bug] stance polarity is missing again on melee weapons

### ISSUE THREAD

**Issue by Melfyce** [WFCD/warframe-items#222]
### Describe the bug

as the title says, all melee weapons are missing the stance polarity again

### NodeJS Version

v14.17.1

### npm Version

7.20.0

### warframe-items Version

v1.1249.13

### Access Method

github download

### What happened?

I believe while fixing this https://github.com/WFCD/warframe-items/issues/214
and implementing this https://github.com/WFCD/warframe-items/pull/216

the stancePolarity property got accidentally kicked out again.

**Comment by TobiTenno** [comment]
ooof

**Comment by TobiTenno** [comment]
yup, i booped it here https://github.com/WFCD/warframe-items/commit/b18598ecc189bc575518fb86d5597a3876df962f#diff-9a34d0e9ba5792f444e19c97f5890f8f95f624d306f216e54d7373a721156e40L676
