### ISSUE TITLE
Warframe Json is showing wrong Vaulted primes

### ISSUE THREAD

**Issue by RGAGRA** [WFCD/warframe-items#233]
### Describe the bug

Vaulted Primes are marked incorrectly

### NodeJS Version

99

### npm Version

99

### warframe-items Version

99

### Access Method

github download

### What happened?

https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Warframes.json
showing Atlas, Nyx, Rhino and Valkry Primes as Vaulted. Hope this is right place to raise the correction request

**Comment by TobiTenno** [comment]
wow, your stuff is mega unhelpful. referencing the master warframes.json (which is generally not openable from the web) references whatever the latest is, not what you downloaded.

they are vaulted. prime unvaultings do not represent something being "no longer vaulted", they are a temporary unvaulting, and as the source of this data does not consider them to be "no longer vaulted" after their original vault date, we don't either.

see [all other mentions of primes in our issues](https://github.com/WFCD/warframe-items/issues?q=is%3Aissue+is%3Aclosed+prime)
