### ISSUE TITLE
[Bug] Incorrect spcification of tradable items

### ISSUE THREAD

**Issue by Everspace** [WFCD/warframe-items#244]
### Describe the bug

Proboscis Cernos and Sevagoth are specified as tradable when they are not

### NodeJS Version

v16.7.0

### npm Version

yarn 1.22.11

### warframe-items Version

1.1249.135

### Access Method

npm Package (Default)

### What happened?

These have `tradable: true` rather than `tradable: false`

**Comment by TobiTenno** [comment]
you can thank DE for being dimwits and using `Prime` in the id for Proboscis Cernos and `Wraith` in the id for Sevagoth. i'm working on refinements.

**Comment by TobiTenno** [comment]
fixes should come soon:tm: with the next release once #247 is resolved...
