### ISSUE TITLE
[Bug] Weapons like the Akaten appear in both Primary.json and SentinelWeapons.json

### ISSUE THREAD

**Issue by Everspace** [WFCD/warframe-items#245]
### Describe the bug

Akaten and similar things are duplicated across the different Jsons.

### NodeJS Version

v16.7.0

### npm Version

yarn 1.22.11

### warframe-items Version

1.1249.135

### Access Method

npm Package (Default)

### What happened?

I expect only 1 of an item to appear across all the "master-able" things.

`/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetMeleeWeaponPS` appears more than once so this caused problems when I was importing all the JSONs, then looping through everything in React.

**Comment by TobiTenno** [comment]
SentinelWeapons is a special case due to them crossing weapon types. we can't just yoink them out of primaries.

**Comment by TobiTenno** [comment]
closed with 3a14f3649e9db141380ecc7f9b2dacaf0a35fae8 (accepted and implemented)
