### ISSUE TITLE
Kavasa Prime Kubrow Collar Buckle/Band missing drops

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#250]
### Describe the bug

Drops are missing for the buckle/band components of the prime kubrow collar

### NodeJS Version

N/A

### npm Version

N/A

### warframe-items Version

v1.1250.4

### Access Method

github download

### What happened?

The Kavasa Prime Kubrow Collar Blueprint has all its drops listed, but the Band and Buckle are missing their drops.

The affected relics:

* Axi B1
* Axi K1
* Lith C1
* Lith K1
* Lith K4
* Lith N2
* Lith S2
* Lith S6
* Meso V3
* Neo N12
* Neo S6

They're listed correctly on the wiki.

I suspect that the issue is related to the names in WFCD data:

Item: "Kavasa Prime Kubrow Collar"  
Blueprint: "Blueprint"  
Band: "Kavasa Prime Band"  
Buckle: "Kavasa Prime Buckle"

Presumably it's looking for e.g. "Kavasa Prime Kubrow Collar Kavasa Prime Band" and not finding it.

**Comment by TobiTenno** [comment]
GitHub download is not supported. Please migrate to a supported method.

that said, i'm taking a look.
