### ISSUE TITLE
Duplicated mods in Mods.json (?)

### ISSUE THREAD

**Issue by IwoHerka** [WFCD/warframe-items#254]
### Describe the bug

It seems that some mods (such as Hawk Eye) are duplicated in the precompiled JSON and have wrong level stats (e.g. Hawk Eye has in once instance +220% Zoom whereas the Wiki lists +80% as max).

### NodeJS Version

-

### npm Version

-

### warframe-items Version

v1.1250.7

### Access Method

github download

### What happened?

It seems that some mods (such as Hawk Eye) are duplicated in the precompiled JSON and have wrong level stats (e.g. Hawk Eye has in once instance +220% Zoom whereas the Wiki lists +80% as max).

**Comment by TobiTenno** [comment]
they're different hawk eyes. it's a problem with their data and we can't do anything about that, as we can't exactly validate arbitrarily which one we "think" is right.
