### ISSUE TITLE
[Bug] Kuva arch-guns' category are set to Primary

### ISSUE THREAD

**Issue by balu92** [WFCD/warframe-items#255]
### Describe the bug

Category for Kuva Ayanga and Kuva Grattler is set to Primary

### NodeJS Version

16.5.0

### npm Version

6.14.13

### warframe-items Version

v1.1250.16

### Access Method

github download

### What happened?

The 2 kuva arch-guns are still in the primary category.
#218

**Comment by TobiTenno** [comment]
feel free to check #260 to see if that'll cover what you're seeing
