### ISSUE TITLE
[Bug] voidrig.png is missing

### ISSUE THREAD

**Issue by balu92** [WFCD/warframe-items#256]
### Describe the bug

Image for the voidrig necramech is missing.

### NodeJS Version

16.5.0

### npm Version

6.14.13

### warframe-items Version

v1.1250.16

### Access Method

github download

### What happened?

Image should be located at: https://raw.githubusercontent.com/WFCD/warframe-items/master/data/img/voidrig.png
But it's 404.

**Comment by TobiTenno** [comment]
yeah, de hasn't actually provided one. it's supposed to be where we fetch it from, but it's not

**Comment by balu92** [comment]
For the record: Requiem mods also missing images.

**Comment by TobiTenno** [comment]
i'm seeing a voidrig-necramech.png, gonna see if the data just got out of sync

**Comment by TobiTenno** [comment]
> For the record: Requiem mods also missing images.

I'm seeing images for one requiem, so at the very least the right one for oull shows, checking others....

Available:
- Oull

Data present, missing image:
- Fass
- Ris
- Jahu
- Khra
- Lohk
- Netra
- Vome
- Xata

Looks like none of the others work, lol. that's useless... checking if they got named wrong too, and I'll try to do a fresh image build to see if those pop up

**Comment by TobiTenno** [comment]
Fixed with my last update for image handling.
