### ISSUE TITLE
:clock1030: Convert warframe-items to ES

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#268]

**Comment by AyAyEm** [comment]
Converting it to ES would break compatibility with commonJs but not the other way around, so why should it be converted?

**Comment by TobiTenno** [comment]
generally? because that's the way js is going in general, so at some point i'll be unable to update dependencies otherwise

**Comment by AyAyEm** [comment]
> generally? because that's the way js is going in general, so at some point i'll be unable to update dependencies otherwise

It depends on the project, but warframe-items only has dev-dependencies so i see no point to update it, unless node is discarding cjs compatibility.

If you're looking for both, maybe a TS rewrite? At least the npm package side of the project isn't large.

**Comment by TobiTenno** [comment]
I'm not converting it to TS.

The purpose is futureproofing for the end of cjs as ES is the standard as of node 12 is moving to EOL.

I still have to be able to upgrade dev-dependencies, and as those move to non-CJS, I have to adapt

**Comment by AyAyEm** [comment]
Could you explain why it would be a good idea to move a library that does not require ES to ES? Sorry, but i'm kind confused here.

**Comment by TobiTenno** [comment]
CJS will continue to be supported, but many large projects are moving their codebases to ES packages and exports, meaning if I don't upgrade, the dev dependencies we use would no longer work.

I have a standing issue out to both notify and help people prepare, because it's simpler to get people started moving the same direction than to drop a bomb when a bunch of my own development packages that I use or maintain end up unusable.

**Comment by AyAyEm** [comment]
I think we're talking about two things here which got both of us confused, i'm talking about the npm package for warframe-items which doesn't have any dependency, and i think you're talking about the build side of the project which does have dependencies. So with that out of the way i do agree that it's best to move the build side to ES but not the package in npm.

**Comment by TobiTenno** [comment]
yeah, for now i don't plan on changing the availability of the package to everyone. sorry for getting so much confusion in there!
