### ISSUE TITLE
Merge with warfarme-wikia-scrapers

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#28]
While we got a very solid basis from the API data, the wikia still has some more data that we should include, so I'd suggest merging [warframe-wikia-scrapers](https://github.com/wfcd/warframe-wikia-scrapers) with this repo.

Some things I can think of off the top of my head:
- [x] Damage distribution (Slash, Puncture, Impact, Elemental)
- [x] Conclave
- [x] Sprint Speed
- [ ] Vaulted state
- [x] Introduced
- [x] Market cost through platinum
- [x] Use "Class" key value for weapon types instead of vaguely guessing.
- [x] Disposition
- [x] Use "traits" key for "tags"

Feel free to edit this comment to add more.

**Comment by TobiTenno** [comment]
This complicates the update of warframe-status (which depends on up-to-date data) when serving the warframe and weapons data...

Do you have any plan as to how you'd want to do that?

**Comment by Kaptard** [comment]
I'm not familiar with how warframe-status is set up - so how would the data changes make things more complicated?

I was thinking that we could just fetch wikia data before getting the API data and then apply additional stuff from the wikia when looping through each item.

**Comment by TobiTenno** [comment]
Right now, when warframe-wikia-scrapers updates, it releases a new version of warframe-worldstate-data and updates warframe-status, trigging a new deployment on heroku.
