### ISSUE TITLE
:rocket: Include ducat cost for prime items

### ISSUE THREAD

**Issue by dstergiou** [WFCD/warframe-items#288]
**Is your enhancement request related to a problem? Please describe.**
Not related to a problem

**Describe the upgrade you'd like**
I think it would be a good idea to add the ducat price of each prime item when sold at a relay

**Describe alternatives you've considered**
No alternatives have been tried

**Comment by dstergiou** [comment]
I just realized the information is there as "primesellingprice" - ignore

**Comment by TobiTenno** [comment]
all good, have a good one.
