### ISSUE TITLE
🚀 Inconsistent casing in polarities key between warframes and weapons

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/warframe-items#289]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the upgrade you'd like**
Change the casing to match between weapons and warframes.

**Additional context**
The problem is in the following polarities: **"umbra", "Umbra", "madurai", "Madurai",  "vazarin", "Vazarin", "naramon" and "Naramon".**

Example:
`{ name: 'Atlas', polarities: [ 'naramon', 'vazarin', 'madurai' ] }`
`{ name: 'Agkuza', polarities: [ 'Vazarin' ] }`

_Note: changed my mind about being a bug, please remove the bug label_

**Comment by TobiTenno** [comment]
not sure i'm a _huge_ fan of this, cause it means transforming DE-provided data, which i'm not a big fan of, but i'll have updates on a PR for people to discuss.
