### ISSUE TITLE
:rocket: Normalize Date values

### ISSUE THREAD

**Issue by AyAyEm** [WFCD/warframe-items#290]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the upgrade you'd like**
Change all the date related strings to one standard.

**Describe alternatives you've considered**
The same in the patchlogs using: `2021-12-07T13:05:12.673Z` or `2021-12-07`

**Additional context**
The dates provided are in the following standards:

- `"item.patchlogs.date": "YYYY-MM-DDTHH:MM:SSZ"` 3309
- `"item.releaseDate": "YYYY-MM-DD"` 1813 items
- `"item.releaseDate": "YYYY MM DD"` 104 items
- `"item.estimatedVaultDate": "YYYY MM DD"` 96 items
- `"item.estimatedVaultDate": "never"` 8 items
- `"item.vaultDate": "YYYY MM DD"` 80 items
- `"item.vaultDate": "n/a"` 16 items
- `"item.vaultDate": "never"` 8 items
- `"item.components.introduced.date":  "YYYY-MM-DD"` 45
- `"item.components.vaultDate": "never"` 2 items
- `"item.components.vaultDate": "YYYY MM DD"` 1 item

**Comment by TobiTenno** [comment]
> - "item.releaseDate": "YYYY-MM-DD" 1813 items
> - "item.releaseDate": "YYYY MM DD" 104 items
> - "item.estimatedVaultDate": "YYYY MM DD" 96 items
> - "item.estimatedVaultDate": "never" 8 items
> - "item.vaultDate": "YYYY MM DD" 80 items
> - "item.vaultDate": "n/a" 16 items
> - "item.vaultDate": "never" 8 items

These dates are maintained by Ogg, not us, we simply consume.


> - "item.patchlogs.date": "YYYY-MM-DDTHH:MM:SSZ" 3309

these are provided by us, and are standarized

> - "item.components.introduced.date": "YYYY-MM-DD" 45

Provided by the wiki
