### ISSUE TITLE
:bug: Inconsistency in labelling as tradeable/untradeable

### ISSUE THREAD

**Issue by ChrisPWilliams** [WFCD/warframe-items#311]
Damaged necramech parts are currently listed as untradeable, which is not true.
Also, prime weapons (and their components) are listed as tradeable, whereas prime warframes are listed as untradeable (but their components are tradeable). Is there any reason for this inconsistency? If it's on DE's end then I guess there's nothing that can be done about it, but if not then could this be cleaned up so that all primes behave the same way?

**Comment by ChrisPWilliams** [comment]
Archwing weapon parts are also erroneously listed as untradeable

**Comment by TobiTenno** [comment]
probably because all of the tradable markers are blocked by #307 causing data to be completely wrong

**Comment by TobiTenno** [comment]
I am seeing the thing with damaged necra parts, so i'm making an exception in the regex for that. still working on prime weapons showing as tradable
i think i'm just missing all the types that they can be, is my guess
