### ISSUE TITLE
Getting sentinel weapon information without using All category

### ISSUE THREAD

**Issue by 3ventic** [WFCD/warframe-items#356]
All.json contains items such as
```json
  {
    "accuracy": 100,
    "ammo": null,
    "attacks": [
      {
        "name": "Normal Attack",
        "speed": 10,
        "crit_chance": 15,
        "crit_mult": 1.5,
        "status_chance": 5,
        "shot_type": "Projectile",
        "shot_speed": 40,
        "flight": 40,
        "damage": {
          "impact": 1.2,
          "slash": 2.4,
          "puncture": 8.4
        }
      }
    ],
    "category": "Primary",
    "criticalChance": 0.15000001,
    "criticalMultiplier": 1.5,
    "damagePerShot": [ 1.2, 8.3999996, 2.3999999, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
    "description": "A Prime Laser Rifle.",
    "disposition": 4,
    "fireRate": 10.000001,
    "imageName": "prime-laser-rifle.png",
    "introduced": {
      "name": "Update 13.7",
      "url": "https://warframe.fandom.com/wiki/Update_13%23Update_13.7",
      "aliases": [ "13.7.0", "13.7" ],
      "parent": "13.7",
      "date": "2014-06-11"
    },
    "magazineSize": 5,
    "masteryReq": 0,
    "multishot": 1,
    "name": "Prime Laser Rifle",
    "noise": "Alarming",
    "omegaAttenuation": 1.21,
    "patchlogs": [
      {
        "name": "Nights of Naberus: Update 30.8.0",
        "date": "2021-10-04T18:05:14Z",
        "url": "https://forums.warframe.com/topic/1283036-nights-of-naberus-update-3080/",
        "additions": "",
        "changes": "",
        "fixes": "Fixed the Prime Laser Rifle icon image in the Inventory appearing the same as its normal variant."
      }
    ],
    "procChance": 0.050000012,
    "productCategory": "SentinelWeapons",
    "releaseDate": "2014-06-11",
    "reloadTime": 1.2,
    "sentinel": true,
    "slot": 1,
    "tags": [ "Prime", "Vaulted" ],
    "totalDamage": 11.999999,
    "tradable": false,
    "trigger": "Auto",
    "type": "Companion Weapon",
    "uniqueName": "/Lotus/Types/Sentinels/SentinelWeapons/PrimeLaserRifle",
    "wikiaThumbnail": "https://static.wikia.nocookie.net/warframe/images/6/6b/PrimeLaserRifle.png/revision/latest?cb=20140718041009",
    "wikiaUrl": "https://warframe.fandom.com/wiki/Prime_Laser_Rifle"
  }
```
with category "Primary", but these items are not included when using `new Items({ category: ['Primary'] })`. They seem to be in their own SentinelWeapons.json file, but there is no category SentinelWeapons.

It's not ideal that I have to use the All category to get these.

**Comment by TobiTenno** [comment]
yes there is... you also seem to have not used the bug template, in the future please do so, so that i don't have to ask all the following:
- version you're on
- access method
- nodejs version
- npm version

[demo runkit](https://runkit.com/tobitenno/615e52157b2af60008dce1f5)

**Comment by 3ventic** [comment]
Seems if you create an issue as a guest and then login it skips the issue template selection. 10/10.

Version is `1.1253.1090` and you can see the code here: https://github.com/3ventic/reimagined-potato/blob/main/src/routes/index.ts

Node v18.3.0
Npm 8.11.0

**Comment by TobiTenno** [comment]
not sure where you're getting this from:
```ts
const categories: Items.Category[] = [
	'Arch-Gun',
	'Arch-Melee',
	'Archwing',
	'Melee',
	'Misc',
	'Pets',
	'Primary',
	'Secondary',
	'Sentinels',
	'Warframes'
];
```
but it's wrong

**Comment by 3ventic** [comment]
That's the list I'm filtering down to. It's a subset of `Category` from this package https://github.com/WFCD/warframe-items/blob/master/index.d.ts#L451

**Comment by TobiTenno** [comment]
yeah, the category as defined isn't 100% accurate in the types. i'll change it momentarily.

**Comment by TobiTenno** [comment]
if you change the types as described in the pr, lemme know if that helps it work for you.

also, now noticing what you're doing, would you be interested in working with me on warframe-hub to make it do what you're making with reimagined-potato?

**Comment by 3ventic** [comment]
I can definitely have a look at that on both accounts.

**Comment by TobiTenno** [comment]
(i'm down to convert hub to typescript, we mostly just do js purely right now)

**Comment by TobiTenno** [comment]
@3ventic lemme know when you get a chance to try it out
