### ISSUE TITLE
:rocket: Exporting Typescript interfaces and types

### ISSUE THREAD

**Issue by Shoonkey** [WFCD/warframe-items#392]
**Is your enhancement request related to a problem? Please describe.**
I'm developing a Discord bot that uses the library using Typescript, and I noticed that even though the API has typings, they're not exported.

**Describe the upgrade you'd like**
I think it'd be really useful to have access to the library types to integrate code better with it.

**Describe alternatives you've considered**
Currently the options I've thought about are either duplicate the necessary types in my own code or access a custom fork of the library where types are exported.

**Additional context**
![image](https://user-images.githubusercontent.com/16379450/203643524-0307a3ed-5cbb-43c9-9e36-462585c9b606.png)

**Comment by TobiTenno** [comment]
We already export types...

**Comment by Shoonkey** [comment]
I see.
For some reason I can't import them from my code. Do you know why this might be happening?

**Comment by TobiTenno** [comment]
@AyAyEm do you have issues importing them?

**Comment by Shoonkey** [comment]
Interesting, it seems like it was my IDE that wasn't finding the types for autocompletion. It's working normally, sorry for the misunderstanding and thanks for the help!
