### ISSUE TITLE
[Bug] canAccess is not defined

### ISSUE THREAD

**Issue by Peatral** [WFCD/warframe-items#404]
### Describe the bug

When trying to get all Warframes, canAccess cant be called

### NodeJS Version

v16.18.1

### npm Version

v8.19.2

### warframe-items Version

v1.1258.15

### Access Method

npm Package (Default)

### What happened?

When trying to do `new Items({category:['Warframes']})` the error `ReferenceError: canAccess is not defined` is thrown. It seems like commit 233ae0e543ab8ce4fff9ad8cc30bc55fb8bbdde9 is to blame for that.

**Comment by TobiTenno** [comment]
thanks for catching this! i'll get right on it. it sounds like you're using it via esm, right? like you're doing `import Items from 'warframe-items';`?

**Comment by TobiTenno** [comment]
should be fixed with b05e8331330808b04cf5989eb2cab3e952a8e5d6.... once it releases, give it a shot!

**Comment by TobiTenno** [comment]
@Peatral sorry it took so long, had to fix some other issues too. should be working now with https://github.com/WFCD/warframe-items/releases/tag/v1.1258.16

**Comment by Peatral** [comment]
Yup, works now again!
