### ISSUE TITLE
Mark components as tradable

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#41]
Lots of tradable items include non-tradable components, which makes it hard to guess which parts are tradable and which aren't.

**Comment by TobiTenno** [comment]
is this something that's included with the data from the exports, or something we need to write a way to determine?

**Comment by Kaptard** [comment]
Every component is actually its own item in the Exports. But normal items have no tradable markers either. We have to guess that by name, category, type and other indicators. The relevant issue for making those more accurate is #5

**Comment by Kaptard** [comment]
Looks like I actually implemented this a few days ago and forgot to close.
