### ISSUE TITLE
:rocket: Add drop locations from syndicates

### ISSUE THREAD

**Issue by SnowyLeopard** [WFCD/warframe-items#411]
**Is your enhancement request related to a problem? Please describe.**
Currently the drop locations for items acquired through syndicates are missing from the dataset. Would like to be able to see if a mod or weapon can be acquired by purchasing it through a syndicate.

For example the `Kaszas Handle` can be purchased at steel meridian. Would like to be able to see this as information on the item.

**Describe the upgrade you'd like**
Extend drop location of items with syndicate wares.

**Additional context**
Since this isn't information available through the drop table it needs to be scraped from the wiki as far as I can tell.
A scraper could be created to parse all wares for a syndicate. Afterwards drop information can be added to items the same way currently done with the other drop location information.

Drop locations could be initially limited to the items already containing drop information, later it could be extended to mods where they at that point also include information as to where to obtain these.

Would be willing to create a PR to implement this if you are OK with the idea!

**Comment by TobiTenno** [comment]
so would you be wanting to implement it as drops @ 100% for the syndicates? the best option would probably be adding a location of 100% in the all.slim.js mapping for syndicate stuff in the WFCD/warframe-drop-data

**Comment by SnowyLeopard** [comment]
@TobiTenno discussed this for a bit on discord with Andre, he also suggested to just add it to the warframe-drop-data package. I was inclined to keep the wiki scraping within warframe-items but the more I think of it it would make more sense to have one source of drop information coming into warframe-items.

I'll create a PR on warframe-drop-data to implement this.

Regarding the structure of the data, I'm fine with adding them as `100%` drop chances, so it would become something like:
- location: syndicate name
- type: item name
- chance: 100
- rarity: syndicate rank and cost information

**Comment by TobiTenno** [comment]
should bubble up with the next build :crossed_fingers:

**Comment by SnowyLeopard** [comment]
I see a new build has been created with the syndicate drops included, awesome! Thanks for the help!

**Comment by TobiTenno** [comment]
Awesome
