### ISSUE TITLE
[Bug] Missing item types

### ISSUE THREAD

**Issue by Mettwasser** [WFCD/warframe-items#427]
### Describe the bug

Resources do not have a type: resource.

### NodeJS Version

n/a

### npm Version

n/a

### warframe-items Version

n/a

### Access Method

warframestat.us API

### What happened?

All the broken types I could spot (that were either typed with something weird or had "Misc")
- Nano Spores
- Alloy Plate
- Salvage
- Rubedo
- Plastids
- Circuits
- Orokin Cell
- Argon Crystal
- Control Module
- Mutalist Alad V Nav Coordinate
- Cryptographic ALU
- Omega Isotope
- Riven Sliver
- Kuva
- Steel Essence
- ~~Isos (completely broke? not Misc/Resource)~~ (2 items same name)
- Morphics
- Cryotic
- Hexenon
- Neural Sensors
- Oxium
- Polymer Bundle
- Tellurium
- Spectral Debris
- Aya
- Somatic Fibers
- Endo
- Nav Coordinate
- Judgement Points
- Synthula
- Javlok Capacitor
- Vitus Essence
- Void Traces
- Gallium
- Antiserum Injector Fragment

**Comment by Mettwasser** [comment]
*adding: the cause for the problem with Isos is that there is a Node in the Star Chart called "Isos" on Eris. Isos as resource is of type Node. Missing something to differentiate?

**Comment by TobiTenno** [comment]
having issues with several of these. one of them being "Endo" isn't an actual item. there are really only bundles...
