### ISSUE TITLE
[Bug] Map method does not work properly with data instance

### ISSUE THREAD

**Issue by wyrmling** [WFCD/warframe-items#442]
### Describe the bug

When using `.map()` method on WFItems instance dataset narrowed by `category` option - mapped array is returned together with full dataset array.

### NodeJS Version

16.14.2

### npm Version

8.9.0

### warframe-items Version

1.1260.50

### Access Method

npm Package (Default)

### What happened?

```js
const quests = new WFItems({
  category: [
    'Quests'
  ]
});
const questNames = quests.map(quest => quest.name);
console.log(questNames.length, questNames)
```
Will print `13000` (instead of `39`) and content of array will be mixed with full dataset.
This happens because `map` method will call array constructor second time and json data will be read from disk again. Probably we have to move fetch logic to separate method:
```js
const quests = new WFItems()
  .get(['Quests']);
```

**Comment by TobiTenno** [comment]
I'm pretty sure we literally have a thing about this in the code or in the readme, lol

**Comment by TobiTenno** [comment]
And no, because that would load literally everything all the time into memory...

**Comment by wyrmling** [comment]
@TobiTenno Sry, but I didn't get you.

BTW, how `Items` class intended to work - for filling DB once?

**Comment by TobiTenno** [comment]
as discussed, this is related to v8 behavior

**Comment by mdpung** [comment]
Side note: Private discussions aren't very effective for helping out other people who have raised similar questions.

**Comment by TobiTenno** [comment]
Well, it was public on our public discord
