### ISSUE TITLE
:rocket: Create a CONTRIBUTE.md

### ISSUE THREAD

**Issue by mdpung** [WFCD/warframe-items#486]
**Is your enhancement request related to a problem? Please describe.**
There isn't any documentation for the current systems and processes in place for contributing to the codebase and making PRs.

**Describe the upgrade you'd like**
Create a CONTRIBUTE.md in the root directory of the project to cover the conventions, steps, and resources that should be noted before contributing to the codebase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TobiTenno** [comment]
this isn't an enhancement, a contributing.md would be net-new.

**Comment by TobiTenno** [comment]
https://github.com/WFCD/.github/blob/main/CONTRIBUTING.md
