### ISSUE TITLE
Every relic is vaulted

### ISSUE THREAD

**Issue by Attula15** [WFCD/warframe-items#496]
According to the json files every relic that the json contains is vaulted.

**Comment by TobiTenno** [comment]
we just inherit vaulted status. if you'd like to replace how we do that, feel free.

**Comment by FelipiMatheuz** [comment]
It's been more than two weeks and still have no solution.
Where this info is collected?

**Comment by TobiTenno** [comment]
https://github.com/search?q=repo%3AWFCD%2Fwarframe-items+%22vaulted+%3D%22&type=code

**Comment by SlayerOrnstein** [comment]
@FelipiMatheuz are you look at a specific relic?

**Comment by TobiTenno** [comment]
@Attula15 please take a look now and see if it's working better for you

**Comment by Attula15** [comment]
@TobiTenno Planning to, but currently I am not near any kind of PC sry.

**Comment by TobiTenno** [comment]
> Planning to, but currently I am not near any kind of PC sry.

@Attula15 any luck?

**Comment by Attula15** [comment]
Yep, its fine. Thank you very much. Sorry for the delay, I have a lot work to do nowdays.

**Comment by TobiTenno** [comment]
Nope, I've got it.
