### ISSUE TITLE
Clean up tradable markers

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#5]
There's a very high chance that not all tradable/untradable items are identified correctly. *Most* should be, but still requires some tweaking. The relevant code snippet can be found at `scraper.addTradable`.

Just a bunch of things I noticed so far:
- [ ] Arcanes
- [x] Excal/Lato/Skana Prime shouldn't be tradable
- [ ] Non-refined ore and other resources shouldn't be tradable
- [ ] Planet nodes shouldn't be considered at all

Please add your own below if you find any other issues.

**Comment by TobiTenno** [comment]
i think we got a lot of this fixed, @Kaptard... for what we haven't, we have the overrides now. these are pretty good examples. The arcanes and refined ores could probably have a type tweak so they show as refined ores and get added as tradeable that way, maybe?

**Comment by FabienPaugois** [comment]
- [ ] Cetus and Fortuna baits shouldn't be tradable
- [ ] Exalted weapons shouldn't be tradable
