### ISSUE TITLE
:rocket: Amend "Introduced" for many items

### ISSUE THREAD

**Issue by LittleBitwise** [WFCD/warframe-items#501]
**Is your enhancement request related to a problem? Please describe.**
Many items in the pre-compiled data are missing the "introduced" (and/or releaseDate) key, probably because they're also missing wikia page data, even though the pages do exist and could be parsed.

**For example, in mods.json:**
Amar/Boreal/Nira's set mods:
https://warframe.fandom.com/wiki/Amar%27s_Anguish
https://warframe.fandom.com/wiki/Amar's_Contempt
https://warframe.fandom.com/wiki/Amar%27s_Hatred

Faction damage mods: (including Primed/Flawed):
https://warframe.fandom.com/wiki/Bane_of_Corpus
https://warframe.fandom.com/wiki/Bane_of_Grineer
https://warframe.fandom.com/wiki/Bane_of_Infested
https://warframe.fandom.com/wiki/Bane_of_Corrupted 

**For example, in arcanes.json:**
https://warframe.fandom.com/wiki/Arcane_Double_Back
https://warframe.fandom.com/wiki/Arcane_Energize
https://warframe.fandom.com/wiki/Arcane_Eruption
https://warframe.fandom.com/wiki/Arcane_Fury

**Describe the upgrade you'd like**
Fill in the missing data from the existing pages. I peeked at the parser implementation and it seems to have code for copying the data, but I don't know the details.

**Additional context**
Here's two JSON files containing all the entries with missing data, though not all of them have wikia pages which is fine.
Mods: https://gist.github.com/LittleBitwise/ea6aeaf1f95412a3391a74548fad849c
Arcanes: https://gist.github.com/LittleBitwise/6a937265aa78999f12f764b823b411a8

**Comment by TobiTenno** [comment]
how exactly are you wanting us to integrate these? this seems like asking us to change them, where you could just fix the introduced dates on the wiki.

**Comment by LittleBitwise** [comment]
The wiki has the correct dates, but those dates don't seem to get parsed. 🙂

The mods I mentioned are also missing their wikiaUrl key, could that be related?

**Comment by TobiTenno** [comment]
did you read the second half of my comment? if they're not coming over from the wiki dump, the wiki has either changed their format, the dates are in an invalid format, or the parser needs to be adapted to the new keys; OR the url name doesn't match the item name. i'm looking at parts of it, but many of these aren't adaptations we can just flex on.

**Comment by LittleBitwise** [comment]
Sorry for not being clear. I did read your comment, both parts of it, and I understand that it's not necessarily something in your control. I opened this issue to bring attention to it, in case it was something caused by the implementation (or reasonably handled), but if the issue is somewhere else then of course that's different.

**Comment by TobiTenno** [comment]
all good, i think i found something at least _related_ to one of my bullet points about the names not matching precisely. that's in review on #502

**Comment by TobiTenno** [comment]
i'd appreciate your review of it so i can at least have some semblance of a review
