### ISSUE TITLE
Ranges on Melee Weapons..

### ISSUE THREAD

**Issue by cswl** [WFCD/warframe-items#53]
I was searching for Weapon Range on melee weapons however I couldnt find any data..

Seems like Warframe Mobile API endpoint doesnt include range either..
http://content.warframe.com/MobileExport/Manifest/ExportWeapons.json

Is there any other way to find ranges on melee weapons?

**Comment by Kaptard** [comment]
Not sure how to handle this tbh. I don't wanna rely on the wiki, so the only other option is datamining, but that would get us on bad terms with DE.

Still wanted to implement some way to override/add values with manual entries, no questions asked where those values are coming from as long as they're accurate. 😛

Closing this in favor of #54
