### ISSUE TITLE
Implement a way to override scraped data with manually gathered values.

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#54]
Title. 

Since we won't have complete coverage with the API alone, I'm suggesting we should add a way to keep a separate file with additional values for items based on their `uniqueName`, which then gets merged with the scraped data.

This would also make it easier to implement exceptions, like Excalibur Prime being the only untradable prime frame.

**Comment by TobiTenno** [comment]
I was thinking about this, I think the easiest way would be keying overrides on unique name, then assigning and spreading the override after all the rest of the assignments have been changed, namely after `this.addDates(item)`.

```js
// in the impotrs
const overrides = require('config/overrides.json')

// at the beginning of the for loop in filter
override = overrides[item.uniqueName]

// after this.addDates(item)
item = {
    ...item,
    ...override
}
```
