### ISSUE TITLE
data/json/Enemies.json is 5 years old, please update

### ISSUE THREAD

**Issue by hortiSquash** [WFCD/warframe-items#557]
### Describe the bug

data/json/Enemies.json is 5 years old, please update

### NodeJS Version

a

### npm Version

a

### warframe-items Version

v1.1262.38

### Access Method

github download

### What happened?

data/json/Enemies.json is 5 years old, please update

**Comment by SlayerOrnstein** [comment]
Warframe-items updates based on public information DE provides. So you gotta go higher up the food chain for this request
