### ISSUE TITLE
'map' does not work as expected on items array

### ISSUE THREAD

**Issue by Sainan** [WFCD/warframe-items#566]
Using 'map' on the items array causes every item to be present in the result, an easy way to see this is by querying 'length':
```JS
const items = new Items({ category: ['Arch-Gun'] });
console.log(items.length);
console.log(items.map((x) => x).length);
```

I've attempted to fix this in #561 by reimplementing the function as was previously done with 'filter', however this fix was seemingly rejected.

Another possible fix would be to not store properties on a class extending Array.

**Comment by TobiTenno** [comment]
closed by #567
