### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by will-janz** [WFCD/warframe-items#58]
I'm making an Angular app using this data (thank you btw) and will be typing out the weapons, pets, frames, etc. I'd like to see types here, I'd be willing to help create them (can't promise any timeline though).

How often does the schema of the data change? Would types be something on the radar and viable?

Thanks!

**Comment by TobiTenno** [comment]
The data schema changes pretty rarely. If you'd like to create typings, feel free to do so and submit a pr.

I don't know that we have explicit plans for them at the moment.

**Comment by will-janz** [comment]
Gotcha. Upon further usage this seems to need more than just types (Angular doesn't like the usual method of importing, though I could be doing it wrong). Closing this, and I'll raise a TS Compatibility issue later on.

Thanks for the info!
