### ISSUE TITLE
:tada: Integration of Riven Dispo

### ISSUE THREAD

**Issue by monster010** [WFCD/warframe-items#593]
**Is your feature request related to a problem? Please describe.**
Actually, everything for the weapons is there in the data, but the riven dispo is missing, which I think is a shame. It would be great if the riven dispo also appeared in the data.

**Describe the solution you'd like**
I saw that there is the following page in the wiki [https://warframe.fandom.com/wiki/Riven_Mods/Weapon_Dispos](https://warframe.fandom.com/wiki/Riven_Mods/Weapon_Dispos) and I know that data from the wiki is used.

**Additional context**
Hope you like the idea and that you can incorporate it.

**Comment by TobiTenno** [comment]
the riven disposition is already in there, it's called "omegaAttenuation" for DE's raw value, and "disposition" for the number of "riven pips" of disposition.

ex: 
https://api.warframestat.us/weapons/search/Boltor/?only=omegaAttenuation,name,uniqueName,disposition
```json
[
  {
    "disposition": 4,
    "name": "Boltor",
    "omegaAttenuation": 1.3,
    "uniqueName": "/Lotus/Weapons/Tenno/Rifle/BoltoRifle"
  },
  {
    "disposition": 4,
    "name": "Boltor Prime",
    "omegaAttenuation": 1.2,
    "uniqueName": "/Lotus/Weapons/Tenno/LongGuns/PrimeBoltor/PrimeBoltor"
  },
  {
    "disposition": 4,
    "name": "Telos Boltor",
    "omegaAttenuation": 1.2,
    "uniqueName": "/Lotus/Weapons/Syndicates/ArbitersOfHexis/LongGuns/AHBoltor"
  }
]
```
