### ISSUE TITLE
[Bug] Relic reward chances

### ISSUE THREAD

**Issue by CloudyBuhtz** [WFCD/warframe-items#602]
### Describe the bug

Reward chances for every relic is the same regardless of refinement

### NodeJS Version

v22.3

### npm Version

10.8.1

### warframe-items Version

1.1262.109

### Access Method

npm Package (Default)

### What happened?

Checked all three sources (Github, warframestat.us and the npm package).

The chance numbers for each of the rewards are always the intact chances regardless of the actual refinement.

Below is a single cut down example from the `Relics.json` with the numbers straight from https://www.warframe.com/droptables aside the current ones. I've not exhaustively checked them, but I'm pretty sure all of the non intact relics have the incorrect chances listed.

```json
...
{
    "category": "Relics",
    "name": "Axi A1 Exceptional",
    "rewards": [
      {
        "rarity": "Uncommon",
        "chance": 11, // 13
        "item": {
            "name": "Akstiletto Prime Barrel",
      },
      {
        "rarity": "Uncommon",
        "chance": 25.33, // 23.33
        "item": {
            "name": "Trinity Prime Systems Blueprint",
        }
      },
      {
        "rarity": "Uncommon",
        "chance": 25.33, //23.33
        "item": {
            "name": "Fragor Prime Head",
        }
      },
      {
        "rarity": "Uncommon",
        "chance": 11, // 13
        "item": {
            "name": "Dual Kamas Prime Handle",
        }
      },
      {
        "rarity": "Uncommon",
        "chance": 25.33, // 23.33
        "item": {
            "name": "Braton Prime Stock",
        }
      },
      {
        "rarity": "Rare",
        "chance": 2, // 4
        "item": {
            "name": "Nikana Prime Blueprint",
        }
      }
...
```

**Comment by TobiTenno** [comment]
we pull the drops data from warframe-drops-data (one of our other libraries) it might just not've gotten updated yet

**Comment by TobiTenno** [comment]
an update just came through, if you want to check in a few hours on the accuracy from the latest update

**Comment by TobiTenno** [comment]
@CloudyBuhtz i'm gonna close this for now, now that they've updated from the drops data update, but if there are more, feel free to comment and i'll readily reopen this.
