### ISSUE TITLE
Various resources missing from Resources.json

### ISSUE THREAD

**Issue by will-janz** [WFCD/warframe-items#62]
"Alertium" and "Nitain Extract" appear nowhere in Resources.json. The `uniqueName` does exist in All.json. 

## Known Missing Resources
* "/Lotus/Types/Items/MiscItems/NeuralSensor"
* "/Lotus/Types/Items/MiscItems/Alertium"

## Tasks
* [ ] Cross-reference Resources.json, All.json, and various API endpoints
* [ ] Determine why resources are missing
* [ ] PR a fix

**Comment by TobiTenno** [comment]
these aren't manually edited, they're likely not included by DE for some reason, that's not really something we can force an update on.

**Comment by will-janz** [comment]
Huh. I'll take a look (when I have time) at what else is missing and see if we can't source it.

**Comment by TobiTenno** [comment]
I'm seeing alertium in our images, and it's definitely present in Misc.json.

I'll see if there's anything from the description that we can parse out to see if it's from a resource, because I think that's what's catching you up.

**Comment by TobiTenno** [comment]
@will-janz i'm going to close this out. feel free to re-open if you find more that are missing.
