### ISSUE TITLE
[Bug] Missing hash on img files

### ISSUE THREAD

**Issue by NicolasFlamel** [WFCD/warframe-items#636]
### Describe the bug

Some images are missing hash

### NodeJS Version

v22.9.0

### npm Version

v10.8.6

### warframe-items Version

v1.1263.40

### Access Method

npm Package (Default)

### What happened?

Most items work but a few have imageNames that don't match up with file names in [data/img](https://github.com/WFCD/warframe-items/tree/bd016c8ea97bcee37b2cf8c32224af2109c822c0/data/img). 

For example, the Akstiletto imageName is akstiletto-5d5e77400c.png, but is just [akstiletto.png](https://github.com/WFCD/warframe-items/blob/bd016c8ea97bcee37b2cf8c32224af2109c822c0/data/img/akstiletto.png)  in data/img.

Other examples that fail to fetch but I did not look into include:
- bolto
- boltor
- bronco-prime: (might be missing entirely) 
- bronco: (might be missing entirely) 
- dual-skana

My guess is that the affected items are all weapons that are used as components to craft other items and that messed up the file naming. If you look at the Akstiletto as a component inside of Aksomati it uses the old imageName akstiletto.png. 

P.S. The current `https://cdn.warframestat.us/img/${item.imageName}` link does not work as the site is currently using the old warframe-items version which has the old imageNames.

**Comment by SlayerOrnstein** [comment]
![image](https://github.com/user-attachments/assets/06ffca49-c328-43ca-9a62-465b1c515720)
![image](https://github.com/user-attachments/assets/8b600fe2-f342-4f0c-87b6-a22329464e06)


Yeah, just have to wait for the cache to either invalidate or purge

**Comment by SlayerOrnstein** [comment]
Oh about Bronco Prime, yeah that's just missing entirely

**Comment by SlayerOrnstein** [comment]
```dart
import 'dart:convert';
import 'package:crypto/crypto.dart';

void main() {
  const uniqueName = '/Lotus/Weapons/Tenno/Pistol/HandShotGun';
  final hash = sha256.convert(utf8.encode(uniqueName)).toString();

// Don't generate for component images, relics, blueprint image, and
// generic arcane entries
  print('https://cdn.warframestat.us/img/branco-${hash.substring(0, 10)}.png');
}
```

Here's a quick work around, it's in dart but that's the gist of it

**Comment by NicolasFlamel** [comment]
Sorry, I might be missing something or it might not have been apparent from the initial message but these issues are happening all locally without the use of the CDN. 

Some of the file names in the repo do not have the hash in the file name. So when when you try to get the image from the repo, for example Branco: [https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/**bronco-65d3eb546d.png**](https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/bronco-65d3eb546d.png), it will give a 404 and instead it will be found without the hash, [https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/**bronco.png**](https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/bronco.png).

**Comment by SlayerOrnstein** [comment]
I think it's Github caching the previous version of the branch due to the size of commit, at least from what I'm seeing

**Comment by SlayerOrnstein** [comment]
Yup, name wasn't sticking due to it being a component not entirely sure why and I'll look more into that one later. I'll try to have a fix out in a few

**Comment by SlayerOrnstein** [comment]
@NicolasFlamel let me know if that fixes things for you. If you use the API you might have to wait till it deploys first

**Comment by NicolasFlamel** [comment]
> @NicolasFlamel let me know if that fixes things for you. If you use the API you might have to wait till it deploys first

@SlayerOrnstein It seems to be partially fixed. While most of the broken ones from earlier are fixed the only ones left are some prime parts that are components of their Ak-weapon versions. These specific weapon image file names now have the word "prime" at the start of the file which contradicts the imageName on the non-ak version of the weapon but match on the component version of the item.

### Affected items
- bronco-prime
- lex-prime
- magnus-prime
- vasto-prime

### Example

I can use the Lex prime as an example to make things clearer. If you look at Lex Prime, it's imageName is "lex-prime-547afa0c65.png" but the matching image file is [prime-lex-prime-547afa0c65.png](https://github.com/WFCD/warframe-items/blob/master/data/img/prime-lex-prime-547afa0c65.png). 

When looking at Aklex Prime then at it's component, Lex Prime, it's imageName is "prime-lex-prime-547afa0c65.png" which matches the file name.

Lex Prime: 
`{ "name": "Lex Prime", "imageName": "lex-prime-547afa0c65.png" }`

Aklex Prime:
`{ "name": "Aklex Prime", "components": [{ "name": "Lex Prime", "imageName": "prime-lex-prime-547afa0c65.png" }] }`
