### ISSUE TITLE
Images url is incorrect.. no images loading

### ISSUE THREAD

**Issue by mrtwebdesign** [WFCD/warframe-items#65]
I'm just getting started and tried listing out the arcanes. The data is fine, but the image url is being redirected to a site that is "down"

Built url as image source:
https://cdn.warframestat.us/img/Exodia-Contagion.png

resulting url after redirect in browser when trying to load reasource:
https://raw.githubusercontent.com/wfcd/warframe-items/development/data/img/Exodia-Contagion.png
Image does not load, getting error instead
"This site can’t be reached"

**Comment by TobiTenno** [comment]
It's likely tied to existing issues we're seeing.

**Comment by TobiTenno** [comment]
@mrtwebdesign I dunno where you're getting the naming from, but it actually works if you take the name from the data itself, which is `exodia-contagion.png`. It looks like your issue was more of a casing issue than a non-existent image issue.
