### ISSUE TITLE
[Bug] Some cdn.warframestat.us/img links are broken

### ISSUE THREAD

**Issue by fburaktrd** [WFCD/warframe-items#652]
### Describe the bug

Some cdn.warframestat.us/img links are broken

### NodeJS Version

v20.4.0

### npm Version

v9.7.2

### warframe-items Version

v1.1263.9

### Access Method

npm Package (Default)

### What happened?

Hi again!

Some cdn.warframestat.us/img links are broken. I could not determine how many paths are broken, but here are the ones I can find so far

![image](https://github.com/user-attachments/assets/c9921f62-8ff2-499f-8c28-5333ca0599d9)
![image](https://github.com/user-attachments/assets/148dbf15-a310-4771-9c10-b96cc0259e33)

**Comment by TobiTenno** [comment]
where are you using this from? are you referencing them directly or pulling the imageName off of the item? if you look at my recent update on https://github.com/wfcd/warframe-hub for steel-essence, that's the kind of lookup you'd be wanting to use.

Also, you specified that you're using npm package, but you're referencing the image url, but don't specify how you got the imageName. please let us know.

**Comment by fburaktrd** [comment]
Hi Tobi,

Sorry for the lack of information. I actually referenced the imageName property in the item object from the warframe-items package. Then I followed the documentation and constructed my url as `https://cdn.warframestat.us/img/${imageName}`.

I checked your commit there and saw that you used the `https://api.warframestat.us/items/search` url to retrieve the image names.

Here is the image name in the response from `https://api.warframestat.us/items/search`
![image](https://github.com/user-attachments/assets/2a6accc6-69ca-46d4-8b87-f8661d42f045)

But it is only rubedo.png in warframe-items package. If I'm not missing anything, I'd be very happy if you could update those imageNames

Also, I liked the way you adjust the images according to url parameters. I think you should definitely mention that in the doc!

**Comment by TobiTenno** [comment]
The API is powered by the node module, so it might be a matter of how you're fetching it from the package or how we're storing it on a particular item.

Could you share a snippet of how you're using the package to get the itemName and we could see if there's something weird about the item that you're getting back that we could update?

**Comment by SlayerOrnstein** [comment]
@fburaktrd looks like you using an older version of warframe-items before #635 was introduced so you're just not pulling in the new data

**Comment by fburaktrd** [comment]
Sorry for the late reply. @SlayerOrnstein , you are absolutely right! When I updated to the latest version I was able to get the new hashed imageNames. Thanks for that!

However, it looks like there is a small problem in the new version (1.1265.0) for the categories. In my current code, I'm using the library as @TobiTenno told me in #630

```JavaScript
const items = new Items({ category: [category] });
```
When I set the category to 'Warframes' it returns a mismatched data, I think.

![image](https://github.com/user-attachments/assets/8194b68b-cc4d-445e-a152-85b10eb5a2b4)

You can see the that 'Helminth' which categorized as "/Lotus/Powersuits/PowersuitAbilities" is returning here.

 I don't know if I should create a new topic for this, please let me know

**Comment by SlayerOrnstein** [comment]
> Sorry for the late reply. @SlayerOrnstein , you are absolutely right! When I updated to the latest version I was able to get the new hashed imageNames. Thanks for that!
> 
> However, it looks like there is a small problem in the new version (1.1265.0) for the categories. In my current code, I'm using the library as @TobiTenno told me in #630
> 
> ```JavaScript
> const items = new Items({ category: [category] });
> ```
> When I set the category to 'Warframes' it returns a mismatched data, I think.
> 
> ![image](https://github.com/user-attachments/assets/8194b68b-cc4d-445e-a152-85b10eb5a2b4)
> 
> You can see the that 'Helminth' which categorized as "/Lotus/Powersuits/PowersuitAbilities" is returning here.
> 
>  I don't know if I should create a new issue for this, please let me know

Funny enough this is working as intended. 

When I added helminth it was under the Warframe category as a separate object with just the abilities. So instead of creating a separate category for helminth abilities I just treated the helminth as a Warframe. 

The unique names are exactly as they are in the public export minus the unique name for helminth which I derived from the unique names of the ability

**Comment by fburaktrd** [comment]
I see, then I'll close the issue. Huge thanks for the clarification and help!

**Comment by TobiTenno** [comment]
Thanks!
