### ISSUE TITLE
Mods don't specify if they are Exilus mods or not

### ISSUE THREAD

**Issue by lassevk** [WFCD/warframe-items#66]
Is that information available somewhere or is that property simply missing from the mod json?

**Comment by TobiTenno** [comment]
so far as i'm aware, it's missing on DE's end, but have not checked thoroughly as of yet.

**Comment by Kaptard** [comment]
Just looked into it and as Tobiah said, there's no identifier for exilus mods

Taking Rush as example:
```
{  
   "uniqueName":"/Lotus/Upgrades/Mods/Sets/Gladiator/MeleeGladiatorRushMod",
   "name":"Gladiator Rush",
   "polarity":"AP_TACTIC",
   "rarity":"COMMON",
   "codexSecret":false,
   "baseDrain":4,
   "fusionLimit":5,
   "description":[  
      "+1s Combo Duration"
   ],
   "type":"MELEE",
   "subtype":"none"
}
```

I'll leave this issue open in case someone wants to check if we can get it from the wikia or other sources.

**Comment by TobiTenno** [comment]
@lassevk if you're interested in adding all of the known exilus mods to our overrides, pick an identifier, find the `uniqueName`s for them, and add, let's call it `isExilus` as a boolean field?
