### ISSUE TITLE
Placeholders in Warframe ability data

### ISSUE THREAD

**Issue by spiekermax** [WFCD/warframe-items#70]
Since the latest update to the JSON data the descriptions of Warframe abilities changed to look like this: 

> "Bleed effects inflicted on enemies do |DAMAGE|% increased damage and last |DURATION|% longer."

I want to use these strings but it is unclear to me where to get the "|DAMAGE|%" values from. Am I missing out on something?

**Comment by TobiTenno** [comment]
those are the scaling ones based on the frames's ability and power, but we don't have replacements for those.

**Comment by spiekermax** [comment]
Is there any way I can retrieve the old strings then?

**Comment by Kaptard** [comment]
You can get the previous data on npm (`warframe-items@1.128.0`) or from [this tree](https://github.com/WFCD/warframe-items/tree/b38a88fac1e8e7c31d53b52846777a1f9ade946f/data/json).

**Comment by spiekermax** [comment]
Thank you so much!

>  However, I'll look into if we can replace these by default with the respective value ranges.

This would help a lot!
