### ISSUE TITLE
[Feature suggestion] add drop tables to relics themselves

### ISSUE THREAD

**Issue by lgutter** [WFCD/warframe-items#73]
Right now, Relics in the `Relics.json` Don't contain any info on what can drop from them.
All this info is available in the items they drop, but that requires a much broader search than just checking the Relic.
If there is a way to easily include the drop tables of a relic (including drop chance), I think it would be a great addition!
the info is here already, all that would be required is copying it over to the relic itself.

**Comment by TobiTenno** [comment]
I think one bit of hesitation would be that if it's so easy, might as well just not do it, because it'd be boilerplate and ultimately just bloat the files

**Comment by Kaptard** [comment]
The Relic files are already too large as they are, adding this redundant information wouldn't be a good choice.

So my suggestion is to add an option to the npm module which populates that data at runtime in-memory. @lgutter Have you perhaps already worked on an algorithm to attach that data since opening this issue?

**Comment by lgutter** [comment]
Sorry for my late response here, I haven't had time to work on the project I've been using this for.
I think you're both right, and perhaps @Kaptard's suggestion is a good solution.
when I have time, I'd definitely like to try and figure out a way attach the data to the relics myself, and perhaps if I find an efficient way to do that it could be integrated in the npm module.
I'm working together with some friends with a lot more experience in in this stuff than me, so I'll see what we can do.
If we have a solution I'll post here again!

**Comment by TobiTenno** [comment]
Alternatively some wrapper in the module to "add relic drops" if the caller so desires, making the data available, that way people who wouldn't use it at runtime don't need that overhead.

**Comment by TobiTenno** [comment]
I'll close this for now, it's not really something we have planned, and it sounds like there's not really any progress towards it soon. If you do, feel free to re-open!
