### ISSUE TITLE
Mods effects aren't suitable for builds consumption.

### ISSUE THREAD

**Issue by cswl** [WFCD/warframe-items#74]
I was trying to make my own build calculator not the whole website stuff.. just a simple one with limited mods..

But the mods dont have such effects listed in a consumable format.. For example..
```
    "uniqueName": "/Lotus/Upgrades/Mods/Rifle/WeaponDamageAmountMod",
    "name": "Serration",
    "polarity": "Madurai",
    "rarity": "Uncommon",
    "baseDrain": 4,
    "fusionLimit": 10,
    "description": "+15% Damage",
    "type": "Rifle",
    "imageName": "serration.jpeg",
    "category": "Mods",
    "tradable": true,
```

+15% Damage .. should be parsed and mods with double effects like
```
    "uniqueName": "/Lotus/Upgrades/Mods/Rifle/DualStat/ElectEventRifleMod",
    "name": "High Voltage",
    "polarity": "Madurai",
    "rarity": "Rare",
    "baseDrain": 4,
    "fusionLimit": 3,
    "description": "+15% <DT_ELECTRICITY>Electricity,+15% Status Chance",
    "type": "Rifle",
    "imageName": "high-voltage.jpeg",
    "category": "Mods",
    "tradable": true,
```

Is there a parser available or should I write my own?

**Comment by TobiTenno** [comment]
Those descriptions are directly from DE, not something we format or parse.

If you'd like to write something within the package that parses descriptions for effects, that would be highly beneficial.

**Comment by cswl** [comment]
I started to categorize mods and seperate patches / drop locations to different modules..
 https://github.com/cswl/wftools-items

I was wondering if a parser was already written..   also checking Warframe mobile app it only shows it like "+15% damage" .. maybe DE justs send the actual mods rank from server for owned mods.. 

Also build site like Tennoware should already have the data .. but I dont think they'd opensource
Could have manually added the data or parsed from Wiki

**Comment by TobiTenno** [comment]
Patch notes already have their own node module that this pulls from.

**Comment by cswl** [comment]
Oww.. didnt notice that.. I might have to look into scraper.js..

**Comment by TobiTenno** [comment]
If you take a look at my recent pr (#77), that would be about how we'd want to parse out the "affectors" for the mod. Could even keep the `<DT_*>` bit in the description and just parse out duplicate bits in the parsing of it.

**Comment by TobiTenno** [comment]
@cswl feel like helping me design what the objects should look like? i'm thinking of doing a bit of work to at least split them into split chunks and parse out stuff we know how they should affect stats

**Comment by TobiTenno** [comment]
looks like they got built out to do that now, probably from a DE update.
