### ISSUE TITLE
Parse Enemy Manifest

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-items#76]
This would allow toolmakers and others looking to attach extra data, such as the enemy drop tables at some point, to correlate data to the enemy.

Endpoint: [`here`](http://content.warframe.com/MobileExport/Manifest/ExportEnemies.json)

**Comment by TobiTenno** [comment]
@Kaptard would you prefer i make a separate project for this? i'd probably do mostly the same things as here, for the sake of consistency, but i worry i'll miss images from being accessible from the same location, since they'd be split between the two repos.

**Comment by Kaptard** [comment]
It's fine if we add this here, especially due to so much duplicate code. The only thing we must add is an option for the `Items` class to turn off enemy data in case somebody really only wants items.

**Comment by TobiTenno** [comment]
Sounds good to me. I'll build it in when I resubmit.

**Comment by TobiTenno** [comment]
Completed in #89
