### ISSUE TITLE
New relics missing drop locations

### ISSUE THREAD

**Issue by ibbmarsh** [WFCD/warframe-items#81]
The relics added for Loki & Volt Prime's unvaulting are missing drop locations. I am not sure when it started, but it is still missing as of v1.290.0 in repo and npm.

See Relic.json, entries for Lith O2, Meso O3, Neo V8, and Axi L4. These are all missing the prop "drops". None of the other unvaulted relics have this issue.

Note that running the build locally caused the drop locations to populate correctly, so it could just be a one-time hiccup.

**Comment by TobiTenno** [comment]
Yeah, it's probably just missing on those builds, and I know Kaptard is working on a refactor, so we'll see about it after that.

**Comment by Kaptard** [comment]
It's fixed in the [refactor/build](https://github.com/WFCD/warframe-items/tree/refactor/build) branch. Will close this issue when merged.

**Comment by Kaptard** [comment]
Merged and will be available on 1.294.0
