### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by powershellwhizz** [WFCD/warframe-items#84]
I am new to node.js and npm so forgive me if I am doing something stupid. 
I have node.js and npm installed, I run the command npm install warframe-items as per the readme. It downloads and installs fine as a module. It is at this point I am not sure if I am doing the next part correctly. I don't know how to access the data. You say "usage" is "const Items = require('warframe-items')", what does that mean? I took a guess by browsing my root folder (so the package is in root\node_modules\warframe-items) and run node. From there I type "const Items = require('warframe-items')" which I assume is meant to load module right? Then when I type "items" and press enter nothing happens. I was expecting to see data, am I doing something wrong?

Sorry if it's a noob question, thanks!

**Comment by powershellwhizz** [comment]
ok figured it out myself. Your doco is missing the ; at the end. I get it that if I knew node.js I would have spotted it myself! Now when I type 'items' I get the message [function: items], what is the correct syntax?

**Comment by TobiTenno** [comment]
semicolons aren't required for javascript

**Comment by TobiTenno** [comment]
if you take a look at the source, it's pretty clear that they're not needed

**Comment by TobiTenno** [comment]
as the docs say:
```js
// this gives you the library
const Items = require('warframe-items')

// this gives you all items
const items = new Items()

// this gives you weapons
const weapons = new Items({ category: ['Weapons'] })
```

**Comment by TobiTenno** [comment]
you'll notice that the first `Items` is capitalized, and `items` is not. the convention for a class variable is `Capitalized` to start, whereas instances are not, like `items` or `weapons`

**Comment by powershellwhizz** [comment]
so...It was because I was a noob, I didn't know javascript was case sensitive - as I said I'm new to it all in general, my background is PowerShell and I did of Delphi a long time ago (PS isn't case sensitive).

It works now that I'm using the correct case :-) thanks Tobi!
