### ISSUE TITLE
Move to new Mobile API

### ISSUE THREAD

**Issue by Kaptard** [WFCD/warframe-items#91]
As pointed out in #90 the mobile app no longer uses the old MobileExport API, but instead gets its data from 
```content.warframe.com/PublicExport/Manifest/<Resource_with_id>```

The id can be retrieved from here
```origin.warframe.com/origin/00000000/PublicExport/index_en.txt.lzma```

Thanks @AlyoshaVasilieva, I couldn't figure out how to get the right number for the origin file without pulling the app every time and it didn't even occur to me that all 0's would work lol

**Comment by TobiTenno** [comment]
ah, goody.

**Comment by Xzandro** [comment]
Is this actively being worked on or is there some help needed? At least the JSON structure seems to be the same as in the old API, so this might be a quick switch.

**Comment by TobiTenno** [comment]
yeah, he's got it in progress, just had to get the compression fixed

**Comment by Xzandro** [comment]
Thanks for you hard work. :)

**Comment by Kaptard** [comment]
You can check the status on the relevant PR (#93)

**Comment by TobiTenno** [comment]
closed w/ #93
