### ISSUE TITLE
Odonata Prime component names are strange

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#95]
In All.json, a Warframe looks like this (item + main components):

```
Valkyr Prime
    Blueprint
    Chassis
    Neuroptics
    Systems
```

and a weapon looks like this:

```
Braton Prime
    Barrel
    Blueprint
    Receiver
    Stock
```

But Odonata Prime looks like this:

```
Odonata Prime
    Blueprint
    Odonata Prime Harness
    Odonata Prime Systems
    Odonata Prime Wings
```

Shouldn't the components *not* have "Odonata Prime" in them? Otherwise if you're trying to build full names for all components you need special handling if prefix already exists.

(Additionally, the Odonata Prime components seem to be missing their ducats?)

**Comment by TobiTenno** [comment]
For non-archwings, they're common components for many things. There's a lot fewer archwings and probably just never got the names filtered. I'll put some tags on it and do a little investigation to see what we can find.

**Comment by TobiTenno** [comment]
Just got a chance to dig a little bit, it looks like all archwings have the same issue with names, as you can see [here](https://github.com/WFCD/warframe-items/blob/development/data/json/Archwing.json#L122) with Amesha. I'm checking if it's just skipping archwings in the santization process.

**Comment by TobiTenno** [comment]
Got it tracked down. We're replacing the `<ARCHWING>` in the names of the items before we do the component matching, so the messy tags are not being removed, which means the name of the archwing itself isn't getting removed.
