### ISSUE TITLE
Detron parts aren't shown

### ISSUE THREAD

**Issue by MrSoundless** [WFCD/warframe-items#96]
The Secondary.json file doesn't have the correct components for Detron. It's missing the receiver and barrel.

**Comment by TobiTenno** [comment]
Thanks for the info. It's most likely an issue on the listed data on DE's end. I don't have a blueprint in the app right now, or i'd check, but i'm guessing it's a mismatch somewhere along the line between an old and newer manifest where it changed (most likely between the original, event-released version and the generally available one from the Harvester).

We'll dig in and see if it's a common pattern we can correct, but we may not be able to for sure.

**Comment by MrSoundless** [comment]
I noticed there are more weapons with this issue. I forgot which ones but if you need them, I can put them here when I find them again.

May I ask where you got the component info from? I've seen wiki scrapers, but I dont think you use them for this since the info there is correct. I also can't find anything component related in http://content.warframe.com/MobileExport/Manifest/ExportWeapons.json

**Comment by TobiTenno** [comment]
as you can see in our build code, we grab it from the manifests that you linked.

**Comment by TobiTenno** [comment]
Sorry for the delay, if you check out [ExportRecipes](http://content.warframe.com/MobileExport/Manifest/ExportRecipes.json) and search for anything that produces `/Lotus/Weapons/Corpus/Pistols/CorpusHandShotgun/CorpusHandCannon`, you'll see that there's two. From what I can tell, we're currently using `/Lotus/Types/Recipes/Weapons/CorpusHandcannonBlueprint` and not `/Lotus/Types/Recipes/Weapons/DetronBlueprint`. If I can find a good way to tell it which to use, that'll work, but I don't know of a good one off the top of my head. Might need to add some sort of filter that we can config to ignore certain blueprints.
