### ISSUE TITLE
Kavasa Prime Kubrow Collar missing ducats

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-items#97]
https://warframe.fandom.com/wiki/Kavasa_Prime_Collar

Band, buckle, and blueprint are 45, 65, 45 ducats according to wiki but not listed in this repo's data.

**Comment by TobiTenno** [comment]
most likely a mismatch between the ducats repo we consume and our naming. ty for letting us know, i'll take a look when i'm able.

**Comment by TobiTenno** [comment]
yeah, looks like it's mismatching cause of the word `Kubrow` in the middle

**Comment by TobiTenno** [comment]
others mentioned we could add it as an override, but we may need to add a way to override a component.

**Comment by esunder** [comment]
I'll look into this one next after my other PR. Don't want to mix 'em! :)
